### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by Burtan** [beryx/badass-jlink-plugin#1]
Hi,
some documentation would be highly appreciated. For me the properties of the JlinkPluginExtension are not clear and the examples don't really tell either.
Thank you!
Best Burtan

**Comment by siordache** [comment]
Documentation is on the top of my todo list. But I have a busy schedule right now, so you will have to wait about a week.

**Comment by siordache** [comment]
Just added the [documentation](http://badass-jlink-plugin.beryx.org/).
