### ISSUE TITLE
Plugin is not compatible with Gradle version lower than 4.5

### ISSUE THREAD

**Issue by gamma** [beryx/badass-jlink-plugin#10]
Please not the above. We're using Gradle 4.3.1 which does not have the API for eg. "HasMultipleValues"

Can you please point out in the documentation which versions are required to use the plugin?

**Comment by siordache** [comment]
I put the following warning in the documentation:

> The plugin requires Java 11 and Gradle 4.8 or newer. While it might work with some combinations of older Java and Gradle versions, these are not officially supported.
