### ISSUE TITLE
Example of using this Badass plugin, jlink and jpackage to build installers

### ISSUE THREAD

**Issue by walec51** [beryx/badass-jlink-plugin#100]
Hi,

I've used your plug-in to build installers from my small desktop app: http://pdf-decorator.walczak.it/
I've also written an article explaining how we migrated to your plugin, jlink and jpackage: https://walczak.it/blog/distributing-javafx-desktop-applications-without-requiring-jvm-using-jlink-and-jpackage

I think this would be a nice addition to your examples sections in the readme :)

**Comment by siordache** [comment]
That's a really nice application! I added your PDF Decorator and a link to your article to the list of examples.
