### ISSUE TITLE
Support omitting specific entries from the mergedModule's module-info

### ISSUE THREAD

**Issue by nemphys** [beryx/badass-jlink-plugin#101]
As mentioned in some other issues (eg #64 or #72), there are cases when the suggestMergedModuleInfo task adds non-desirable entries to the module-info file, which cause build issues.
It would be nice to have a configuration option to selectively *disable* those entries, instead of having to keep a hard-coded version of the module-info entries (using the mergedModule block) in the build.gradle file (something like the opposite of the additive option, that could be used along with it).

**Comment by siordache** [comment]
I finally found the time to implement this feature in [release 2.17.0](https://badass-jlink-plugin.beryx.org/releases/2.17.0/#_mergedmodule)

Example usage:
```
jlink {
    mergedModule {
        excludeRequires 'java.compiler', 'java.rmi'
        excludeUses 'org.apache.logging.log4j.message.ThreadDumpMessage.ThreadInfoFactory'
        excludeProvides servicePattern: 'org.apache.logging.*'
    }
    ...
}
```

**Comment by nemphys** [comment]
Thanks, you rock :-)
