### ISSUE TITLE
Package modular JavaFX application with Spring Boot

### ISSUE THREAD

**Issue by mockbirds** [beryx/badass-jlink-plugin#103]
I have simple modular JavaFX project using Spring Boot and want to package it as macOS application bundle (.app) and installer package (.pkg). I have no problems building und running the app with `./gradlew build` and `./gradlew run`.

Running `./gradlew jpackage` raised a lot of error messages and I could already reduce them by applying some recommendations from other issue solutions. Like adding

```
dependencies {
...
    implementation 'javax.servlet:javax.servlet-api:4.0.1'
...
}

jlink {
...
    mergedModule {
        additive = true
        uses 'ch.qos.logback.classic.spi.Configurator'
    }
    forceMerge('log4j-api')
...
}
```
I also tried to reanable the normal jar creation since Spring Boot seems to disable it by default but had no luck. I guess I have to repackage the Springs boot jar somehow.

Since I'm a Spring Boot and Java module system newbie it would be great to have a working sample project. Maybe you can have a look at my project at github:

https://github.com/mockbirds/javafx-springboot-badass-jlink

For development I use:

- IntelliJ IDEA 2019.2.4
- Gradle 6.0.1
- AdoptOpenJDK 13.0.1 with HotSpot
- OpenJDK 14 EA Build 14-jpackage+1-7 (https://jdk.java.net/jpackage/)

Many thanks, Steffen

**Comment by siordache** [comment]
I submitted a [pull request](https://github.com/mockbirds/javafx-springboot-badass-jlink/pull/1) with the required adjustments. I only tested it on Windows and Linux, but it should also work on macOS.

I also added a link to your project in the examples section of the plugin.

**Comment by mockbirds** [comment]
Thank you, Serban, for taking the time to fix this.! It's also working on macOS.
