### ISSUE TITLE
mergedModule 'provides' results in 'error: cannot find symbol'

### ISSUE THREAD

**Issue by rashaverak** [beryx/badass-jlink-plugin#104]
Hello, my initial error

`/home/lukas/projects/x/build/jlinkbase/tmpjars/x.merged.module/module-info.java:436: error: module not found: java.xml.ws
    requires java.xml.ws;`

When I add following

`mergedModule {
        additive = true
        forceMerge "jakarta.xml"
    }`

I get 

```
/home/lukas/projects/x/build/jlinkbase/tmpjars/x.merged.module/module-info.java:465: error: cannot find symbol

provides org.codehaus.stax2.validation.XMLValidationSchemaFactory.relaxng with com.ctc.wstx.msv.RelaxNGSchemaFactory;`
                                                                     
 symbol:   class relaxng

  location: class XMLValidationSchemaFactory

/home/lukas/projects/x/build/jlinkbase/tmpjars/x.merged.module/module-info.java:467: error: cannot find symbol

    provides org.codehaus.stax2.validation.XMLValidationSchemaFactory.w3c with com.ctc.wstx.msv.W3CSchemaFactory;
                                                                     
  symbol:   class w3c

  location: class XMLValidationSchemaFactory

/home/lukas/projects/x/build/jlinkbase/tmpjars/x.merged.module/module-info.java:471: error: cannot find symbol

    provides org.codehaus.stax2.validation.XMLValidationSchemaFactory.dtd with com.ctc.wstx.dtd.DTDSchemaFactory;
                                                                     
  symbol:   class dtd

  location: class XMLValidationSchemaFactory

3 errors

```
forceMerge "stax2" does not help

**Comment by siordache** [comment]
Would it be possible for you to upload your project (or a simplified version that allows reproducing the problem) on GitHub?

**Comment by rashaverak** [comment]
I will try to prepare simplified version and let you know till tommorow if it is possible or not.

**Comment by rashaverak** [comment]
You will find the simplified project in here
https://github.com/rashaverak/SimpleSampleBadassJlink

When I run jlink task I can reproduce the issue. java 13

**Comment by siordache** [comment]
For the simplified project, the `jlink` task succeeds if you replace the original mergedModule block with the following one:

    mergedModule {
        requires 'java.management';
        requires 'java.naming';
        requires 'java.logging';
        requires 'java.sql';
        requires 'java.xml';
        requires 'java.desktop';
        requires 'java.datatransfer';
        requires 'java.compiler';
        requires 'java.security.jgss';
        requires 'jdk.unsupported';
        uses 'java.nio.file.spi.FileSystemProvider';
        provides 'javax.servlet.ServletContainerInitializer' with 'io.sentry.servlet.SentryServletContainerInitializer';
        provides 'javax.xml.stream.XMLEventFactory' with 'com.ctc.wstx.stax.WstxEventFactory';
        provides 'javax.xml.stream.XMLOutputFactory' with 'com.ctc.wstx.stax.WstxOutputFactory';
        provides 'com.fasterxml.jackson.core.JsonFactory' with 'com.fasterxml.jackson.dataformat.yaml.YAMLFactory';
        provides 'com.fasterxml.jackson.core.ObjectCodec' with 'com.fasterxml.jackson.databind.ObjectMapper';
        provides 'javax.xml.stream.XMLInputFactory' with 'com.ctc.wstx.stax.WstxInputFactory';
    }


To obtain the above mergedModule I executed  `./gradlew suggestMergedModuleInfo` and then I removed the problematic `provides` clauses.

The resuting mergedModule block is a bit ugly. There is already a [feature request](https://github.com/beryx/badass-jlink-plugin/issues/101) to support omitting specific entries from the mergedModule. I will try to implement this feature in the next few days.

**Comment by siordache** [comment]
With badass-jlink-plugin 2.17.0 you can configure the mergedModule as follows:

    mergedModule {
        excludeRequires 'java.jws'
        excludeProvides servicePattern: 'org.codehaus.stax2.*'
    }

See also [this PR](https://github.com/rashaverak/SimpleSampleBadassJlink/pull/1/commits/674cd16523958933e6be8193c349f1fb67997659).
