### ISSUE TITLE
jpackage installerType = "deb" still running --type app-image

### ISSUE THREAD

**Issue by rashaverak** [beryx/badass-jlink-plugin#105]
Hello, me again.

Now I have problems with the jpackage task.

this is run by jpackage task
`jpackage --type app-image --dest /home/lukas/projects/x/x/build/x --name x --module-path /home/lukas/projects/x/x/build/jlinkbase/jlinkjars --module x/x --runtime-image /home/lukas/projects/x/x/build/image --linux-deb-maintainer hello@x --linux-app-release 1.8.0`

altough I state I want deb

```
jpackage {
        jpackageHome = findProperty("jpackage.path")
        outputDir = someDir
        imageName = someImageName
        skipInstaller = false
        installerName = someInstallerName
        installerType = "deb" //exe, msi, dmg, rpm, pkg, deb
        imageOptions = ['--linux-deb-maintainer hello@x', "--linux-app-release ${appVersion}"]
    }
```

as you can see I have there deb imageOptions but because --type app-image is called the whole task fails 

`Error: Option [--linux-deb-maintainer] is not valid with type [app-image]`

**Comment by rashaverak** [comment]
Another issue appVersion in the task does not make it to the final command.

**Comment by siordache** [comment]
Replace
```
imageOptions = ['--linux-deb-maintainer hello@x', "--linux-app-release ${appVersion}"]
```
with
```
installerOptions = ['--linux-deb-maintainer', 'hello@x.org', '--linux-app-release', project.appVersion]
```

I also submitted the changes as [pull request](https://github.com/rashaverak/SimpleSampleBadassJlink/pull/1).
