### ISSUE TITLE
Flyway's classpath and Hibernate's module access via jrt problem when using jlink

### ISSUE THREAD

**Issue by VictorAtPL** [beryx/badass-jlink-plugin#107]
I am using JavaFX with Hibernate and Flyway.

While I use `run` task in Gradle, everything works as expected.
When I build a Java image via `jlink` task and run the application from *build/image/bin* directory, I got following logs (+ `build.gradle` file):
https://gist.github.com/VictorAtPL/82ceee3f70bf25c900a3099e2a44ad52

Migration files from Flyway are placed `build\resources\main\db\migration`, so I guess they are included after using `jlink`.

More information here on stackoverflow:
https://stackoverflow.com/questions/59902719/flyway-is-not-able-to-find-migrations-in-classpath-only-if-i-run-application-aft?fbclid=IwAR3S7aDVHIVXrwOLdv_Xa1Mc5tX5Ij5AcpV0BdPKTcFO_-_v2dxWtz29NCk

**Comment by siordache** [comment]
Sorry for the late reply. I answered on [stackoverflow](https://stackoverflow.com/a/59956474/2039982) and also submitted ny proposed solution as a [pull request](https://github.com/VictorAtPL/jlink_badass_flyway_classpath_problem/pull/1).

**Comment by VictorAtPL** [comment]
I fixed it similar way. I just copy `.sql` files of Flyway to `build/image/` and load migrations from filepath instead of classpath. Thank you.

Basically it doesn't look as problem of this plugin, but other plugins or explicitly Jigdaw, so I will close this issue. Maybe I will open an issue in Flyway's Github to really get know why it works differently in both scenarios.
