### ISSUE TITLE
Jlink fails with Hibernate

### ISSUE THREAD

**Issue by x7lib** [beryx/badass-jlink-plugin#108]
I m trying to build a project that use Hibernate ORM , and JavaFX13 with JDK13 , The JLink task fails whenever i start to use Hibernate ,telling me `error: module not found: java.xml.bind    requires java.xml.bind;`
and give the following output : 

   
   
    > Task :createMergedModule
    Cannot derive uses clause from service loader invocation in: org/hibernate/boot/registry/classloading/internal/ClassLoaderServiceImpl.loadJavaServices().
    Cannot derive uses clause from service loader invocation in: org/mariadb/jdbc/authentication/AuthenticationPluginLoader.<clinit>().
    Cannot derive uses clause from service loader invocation in: org/mariadb/jdbc/credential/CredentialPluginLoader.<clinit>().
    D:\projetcs\Assurance Mallahi\treporteur\build\jlinkbase\tmpjars\com.x7lib.merged.module\module-info.java:517: error: module not found: java.xml.bind
        requires java.xml.bind;
                         ^
    1 error
    
    > Task :createMergedModule FAILED
 

 my **gradle.builde** file

     plugins {  
      id 'java'  
      id 'application'  
      id "org.openjfx.javafxplugin" version "0.0.8"  
      id "org.beryx.jlink" version "2.17.0"  
    }  
      
    group 'com.x7lib'  
    version '1.0-SNAPSHOT'  
      
    dependencies {  
      // https://mvnrepository.com/artifact/mysql/mysql-connector-java  
      compile group: 'org.mariadb.jdbc', name: 'mariadb-java-client', version: '2.5.3'  
      compile group: 'org.hibernate', name: 'hibernate-core', version: '6.0.0.Alpha2'  
      
      
    }  
      
    repositories {  
      mavenCentral()  
    }  
      
    dependencies {  
      testCompile group: 'junit', name: 'junit', version: '4.12'  
      
    }  
      
    javafx {  
      modules = ['javafx.controls', 'javafx.fxml']  
        version = "13"  
    }  
    jlink {  
      options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']  
      launcher {  
      name = 'TReporteur'  
      }  
    }  
    mainClassName = 'org.x7lib.App'  
    applicationName = 'TReporteur'

while the `module-info` i m using : 

    module org.x7lib {  
    			     requires javafx.controls;  
    				 requires javafx.fxml;  
    				 requires org.mariadb.jdbc;  
    				 requires java.sql;  
    				 requires org.hibernate.orm.core;  
    				 opens org.x7lib to javafx.fxml;  
    				 exports org.x7lib;  
    }
the link to my SuggestMergedModuleInfo : 

> [https://gist.github.com/x7lib/97524111e484075bbe7ac6c72dd04a90](https://gist.github.com/x7lib/97524111e484075bbe7ac6c72dd04a90)

i would be grateful to any help

**Comment by x7lib** [comment]
JLink worked after adding 
`    forceMerge 'jaxb', 'istack', 'stax' `
and the output of suggested MergeModuleInfo to  `MergedModule{...}`

but i still have a problem after adding JasperReports the jlinks output this : 
```
error: the unnamed module reads package javax.xml from both xml.apis and java.xml
error: the unnamed module reads package javax.xml.datatype from both xml.apis and java.xml
error: the unnamed module reads package javax.xml.namespace from both xml.apis and java.xml
...
```

**Comment by siordache** [comment]
Sorry for not being able to reply sooner. The [comment of @VictorAtPL](https://github.com/beryx/badass-jlink-plugin/issues/109#issuecomment-578103211) describes the right way to approach this kind of issues: you need to find where the libraries containing the problematic package appear in the dependency graph and exclude one of them. The plugin cannot fix split package problems by itself.
