### ISSUE TITLE
jlink get confused when a module is  used in more than One module

### ISSUE THREAD

**Issue by x7lib** [beryx/badass-jlink-plugin#109]
JLink worked after adding 
`    forceMerge 'jaxb', 'istack', 'stax' `
and the output of suggested MergeModuleInfo to  `MergedModule{...}`

but i still have a problem after adding JasperReports the jlinks output this : 
```
error: the unnamed module reads package javax.xml from both xml.apis and java.xml
error: the unnamed module reads package javax.xml.datatype from both xml.apis and java.xml
error: the unnamed module reads package javax.xml.namespace from both xml.apis and java.xml
...
```

_Originally posted by @x7lib in https://github.com/beryx/badass-jlink-plugin/issues/108#issuecomment-577673394_

**Comment by x7lib** [comment]
@siordache  hello sorry for bothering but i really need help

**Comment by VictorAtPL** [comment]
Not sure, but maybe `org.mariadb.jdbc` or `org.hibernate` loads `xml.apis` and you need to exclude some specific library which uses it?

For example, I had to use something like this with Hibernate & Lucene:
```
    implementation 'org.hibernate:hibernate-search-orm:5.11.4.Final', {
        exclude group: 'org.apache.lucene', module: 'lucene-misc'
    }
```

Could you provide the result of `dependencies` task?

**Comment by x7lib** [comment]
@VictorAtPL   thanks for your answer , 
 i solved the issue by changing the to the mysql driver ( since mariadb is just a fork of the mysql" 
also made my own homemade  ORM for this project , waiting for the this plugin to get Updated .
although it helps a lot.
anyway thanks
