### ISSUE TITLE
The purpose of -p "$DIR/../app" in bash script generated by jlink task

### ISSUE THREAD

**Issue by VictorAtPL** [beryx/badass-jlink-plugin#110]
After I execute `jlink` task, in `.sh` and `.bat` files generated during execution I can find `-p "$DIR/../app"` in this line:

```
"$DIR/java" -p "$DIR/../app" -m kreator_konspektow_at/app.Main  "$@"
```

Where does it point? I don't see any `app` directory in the `build/image` path. I am struggling with `classloader`, so this information could be helpful.

**Comment by siordache** [comment]
The `app` directory is created only when using the [customImage](https://badass-jlink-plugin.beryx.org/releases/latest/#_customimage) block, which lets you create a custom runtime image containing only some of the modules required by your application (see the [initial feature request](https://github.com/beryx/badass-jlink-plugin/issues/50#issuecomment-490015482)). The plugin puts the modules not included in the custom runtime image in the `app` subdirectory of `image`:
```
image
 ├───app
 ├───bin
 ├───conf
 ├───legal
 └───lib
```

You probably don't use `customImage` in your project, so no `app` directory is created. This means that you can safely ignore the `-p "$DIR/../app"` option. It has no effect.

**Comment by VictorAtPL** [comment]
Ok, now I got it. I think it would be nice to add something about that to the documentation, or even don't add this argument when not using `customImage` block. But so far, I treat this question as answered.
