### ISSUE TITLE
resources not included in jpackage installer

### ISSUE THREAD

**Issue by rrva** [beryx/badass-jlink-plugin#117]
When running the `jpackage` task in https://github.com/rrva/collabster the resulting dmg and pkg installers are missing the fxml resource files. How do I add them?

**Comment by siordache** [comment]
You put your fxml files in the directory `se/svt/videocollab/collabster`, which doesn't match the package name of `CollabsterView`. Move the fxml files into `src/main/resources/se/rrva/collabster`. 

Also, you can remove the `sourceSet` block from your `build.gradle.kts`. Gradle includes `src/main/resources` automatically.

**Comment by rrva** [comment]
sorry, the inconsistent package name came from a version of the repo where I changed that, but I had the same issue before doing that. It seems removing the sourceSet from build.gradle.kts was the thing fixing the problem.
