### ISSUE TITLE
Customizing jpackage app icon

### ISSUE THREAD

**Issue by rrva** [beryx/badass-jlink-plugin#118]
I want to customize the app icon adding `--icon src/main/resources/java.icns` to the jpackage image options using

```kotlin
jlink {
  jpackage {
        imageOptions = listOf("--icon", "src/main/resources/java.icns")
    }
}
```

But I only get the default icon no matter what. 

When I run ./gradlew jpackage --debug, it prints among other things

`Output property 'destinationDir' file /Users/rrj/ee/collabster/build/resources/main/java.icns has been removed.`

Sample repo at https://github.com/rrva/collabster

**Comment by siordache** [comment]
jpackage doesn't accept the `icns` format. You can use an [online converter](https://www.coolutils.com/online/ICNS-to-ICO#) to create a proper `.ico` file and use it for your application.

**Comment by rrva** [comment]
A quick search in the jpackage source code does seem to indicate icns support:

https://github.com/AdoptOpenJDK/openjdk-jdk/search?p=1&q=icns&unscoped_q=icns

Also, the output of the jpackage tool mentions that I can use $appname.icns to customize i.e collabster.icns in my case.

 I am using JDK 14 build 36 from https://jdk.java.net/14/ for OSX

**Comment by rrva** [comment]
```
$  /Users/rrj/jdk-14.jdk/Contents/Home/bin/jpackage --verbose --type app-image --dest /Users/rrj/ee/collabster/build/jpackage --name collabster --module-path /Users/rrj/ee/collabster/build/jlinkbase/jlinkjars --module collabster/se.rrva.collabster.CollabsterApp --runtime-image /Users/rrj/ee/collabster/build/image --icon src/main/resources/java.icns
WARNING: Using incubator modules: jdk.incubator.jpackage
Creating app package: collabster.app in /Users/rrj/ee/collabster/build/jpackage
Using custom package resource [icon] (loaded from file /Users/rrj/ee/collabster/src/main/resources/java.icns).
Preparing Info.plist: /Users/rrj/ee/collabster/build/jpackage/collabster.app/Contents/Info.plist.
Using default package resource Info-lite.plist.template [Application Info.plist] (add Info.plist to the resource-dir to customize).
Using default package resource Runtime-Info.plist.template [Java Runtime Info.plist] (add Runtime-Info.plist to the resource-dir to customize).
Succeeded in building Mac Application Image package
```

but, I might be wrong and will try to convert to .ico

**Comment by siordache** [comment]
I think you're right. The icns format should be supported on OSX. I don't have a Mac and I only tested it on Windows, where I got the warning message: `The specified icon "src\main\resources\java.icns" is not an ICO file and will not be used. The default icon will be used in its place`. It's actually no surprise that it doesn't work on Windows, but I don't know why it doesn't work on OSX. It may be a bug in jpackage itself. I'm curious, though, if it works with an .ico file (it does on Windows).

**Comment by siordache** [comment]
@rrva See #148. Configuring `--resource-dir` probably also solves your problem.

**Comment by mrlimbic** [comment]
Did you get this solved? I can make the application icon change to my own on mac but jpackage still uses the default java icon for the disk image it puts the application on which is annoying.

**Comment by larsroe** [comment]
From my experience, you can't set the pkg and dmg file images-- they will always be the Mac default.

But the application itself (.app) should have the icon specified by either --icons or --resource-dir, and not the Java coffee icon.

**Comment by mrlimbic** [comment]
--icon also set the .app and DMG icon for me but --resource-dir only changed the .app icon. Not sure why.

**Comment by koppor** [comment]
`--icon` works well here: https://github.com/JabRef/jabref/blob/9c4ca38f50e3aa042bc63e922f449cde739861b2/.github/workflows/deployment.yml#L204

Thus, this issue can be closed, can't it?
