### ISSUE TITLE
OpenJDK 14 support (will require Gradle 6.3)

### ISSUE THREAD

**Issue by msgilligan** [beryx/badass-jlink-plugin#121]
The current latest released Gradle is version 6.2.1 and does not work with OpenJDK 14 (EA)

Gradle 6.3 (which will use Groovy 2.5.10) is on the way and will fix the issue.

I updated my SupernautFX project to use a pre-release JDK (see https://github.com/ConsensusJ/SupernautFX/commit/db62578e01c63fa88cf21201f72022868cffbffc) and was able to successfully build macOS, Windows, and Linux binaries with version `2.7.1` of this plugin.

I haven't done much testing, but it looks like we'll be ready for JDK 14 / Gradle 6.3 when they are released.

Here are the successful Github Actions builds: https://github.com/ConsensusJ/SupernautFX/actions/runs/49194097

Note: Links above just updated to point to a cleaner branch:
https://github.com/ConsensusJ/SupernautFX/compare/msgilligan-jdk14-take2

**Comment by msgilligan** [comment]
I went ahead and merged JDK 14 support into the `master` branch of SupernautFX now that **Gradle** 6.3-rc-1 is out: https://github.com/ConsensusJ/SupernautFX/commit/aad611dd4b18aa0257adf43fcc87be503116301f.

**Comment by msgilligan** [comment]
Gradle 6.3 and OpenJDK 14 seems to be working pretty well, so far. One thing I want to do is try to use the `jpackage` command directly from `$JAVA_HOME` -- especially now that JDK 14.0.1 is released (which should fix a bug with signing on macOS)

After I do that, I'll probably close this issue.

**Comment by msgilligan** [comment]
I was going to close this, but I just noticed that JDI 14.0.2 seems to be breaking under *macOS*:
https://github.com/SupernautApp/SupernautFX/runs/905337855

(Reverting to 14.0.1 seemed to fix the problem)

**Comment by siordache** [comment]
It [worked on my clone](https://github.com/to-be-deleted/SupernautFX/runs/912106507?check_suite_focus=true), it seems to be an intermittent failure caused by a "resource busy error".
See also [this discussion](https://bugs.openjdk.java.net/browse/JDK-8245311?focusedCommentId=14355159&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14355159): a patch that repeats `hdiutil detach` several times [is already available](http://cr.openjdk.java.net/~almatvee/8245311/webrev.01/open.patch).

**Comment by mitm001** [comment]
This error is thrown when using OpenJdk 14, gradle 6.3+ and windows or linux. This also happens using a workflow on github and badass.

```
 error: ';' expected
    provides org.codehaus.groovy.runtime.ExtensionModule with extensionClasses=org.codehaus.groovy.jsr223.ScriptExtensions,org.codehaus.groovy.runtime.NioGroovyMethods,org.codehaus.groovy.runtime.SqlGroovyMethods,org.codehaus.groovy.runtime.SwingGroovyMethods,org.codehaus.groovy.runtime.XmlGroovyMethods,
```
