### ISSUE TITLE
IIORegistry lookup

### ISSUE THREAD

**Issue by gringofe** [beryx/badass-jlink-plugin#124]
Hello, 

I am currently using your plugin and [this library](https://github.com/haraldk/TwelveMonkeys) which improves the `ImageIO` class; This works, as described [here](https://github.com/haraldk/TwelveMonkeys#faq), using Javas `IIORegistry` class which searches for plugins;

The library works fine (i'm using Gradle) in Intellij but when I package my app it just doesn't register the plugin. How can I resolve this problem?

**Comment by siordache** [comment]
Maybe you forgot to add a `requires`clause for the imageio module in your module-info.java?

I created an [example application](https://github.com/beryx-gist/badass-jlink-example-imageio-hdr) that uses the TwelveMonkeys library to display an HDR image. If this doesn't help you to fix your problem, please upload to GitHub an example project that reproduces the issue.

**Comment by gringofe** [comment]
Hello,
thanks for your fast response.

I have the requires clause in my moduleinfo; I tried a few things with your demoproject and when I remove the `org.javamodularity.moduleplugin` plugin from your project, it does not recognize the requires clause for `requires imageio.hdr;` anymore (strangely it does in my project without the plugin). After that, I tried adding the modularityplugin to my project, which fails because there seems to be a conflict/or some sort of error with the javafxplugin im using (since my project is a javafx app)

(This is the exception:
`An exception occurred applying plugin request [id: 'org.openjfx.javafxplugin', version: '0.0.8']
> Failed to apply plugin [id 'org.openjfx.javafxplugin']
   > Could not create task ':configJavafxRun'.
      > Could not create task of type 'ExecTask'.
         > Could not generate a decorated class for class org.openjfx.gradle.tasks.ExecTask.
            > org/javamodularity/moduleplugin/tasks/ModuleOptions`)

**Comment by siordache** [comment]
The javafxplugin applies the modularityplugin by itself. So, if you use the javafxplugin you should not explicitly add the modularityplugin.

But in order to help you, please upload your project (or a simplified version of it) to GitHub.

**Comment by gringofe** [comment]
I created [this javafx test project](https://github.com/gringofe/imageio-jlink-test) which prints the imageio plugins 

When I run it in Intellij, it prints
`
reader: com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader@59606a1a
reader: com.sun.imageio.plugins.jpeg.JPEGImageReader@580a4037
`

but when I run the jlink image it only prints 
`reader: com.sun.imageio.plugins.jpeg.JPEGImageReader@7d917cee`

**Comment by siordache** [comment]
Thanks! It was a bug in the plugin. It's fixed in 2.17.3. Give it a try!

**Comment by gringofe** [comment]
Works perfectly, thank your so much!
