### ISSUE TITLE
Feature to print out jlink and jpackage commands to the console

### ISSUE THREAD

**Issue by SohamGovande** [beryx/badass-jlink-plugin#126]
It would be great if this gradle plugin allowed one to see which jlink and jpackage calls were being run under the hood, which is crucial for debugging purposes. For example, you could have a property called `showDebugInfo`, which (if `true`) would create a file called `jlink-plugin-log.txt` with the system calls to jlink and jpackage that are being made.

Thank you!

**Comment by siordache** [comment]
You can see the jlink and jpackage calls if you run gradle with the `-i` (or `--info`) flag. The lines containing these calls start with `Starting process`. Try for example:
```
./gradlew -i clean jpackage | grep 'Starting process'
```

**Comment by SohamGovande** [comment]
I will try this. Thank you!

**Comment by SohamGovande** [comment]
Yep, this is working.

Might I ask, is there a way to see the output from the actual jpackage command?

**Comment by siordache** [comment]
With the `-i` flag, gradle also displays the output of the jpackage commands. However, jpackage doesn't print much by default. To see more, you can use the `--verbose`  option:
```
jlink {
    ...
    jpackage {
        ...
        imageOptions += '--verbose'
        installerOptions += '--verbose'
    }
}
```

**Comment by SohamGovande** [comment]
Great - thanks.
