### ISSUE TITLE
jlink fails on MacOS & Linux

### ISSUE THREAD

**Issue by JamzTheMan** [beryx/badass-jlink-plugin#128]
When running jlink (or jpackage running jlink) on Mac/Linux actions, I'm getting the following error when running against a os matrix on GitHub Actions:

```
* What went wrong:
Execution failed for task ':jlink'.
> java.io.FileNotFoundException: /home/runner/work/TokenTool/TokenTool/build/image/bin/TokenTool (No such file or directory)
```

Listing the `build/image` dir I see that the `bin` dir is missing. This works ok on windows.

Everything works ok on Windows 10 desktop.
Pulling this down to my Mac Mojave laptop, I'm seeing the same issue.  If I'm quick and copy the `bin` dir manually (after jlink cleans and recreates image folder) everything works ok.

Also, after manually copying the `bin` dir, jpackage command works as well until `image` dir is cleaned/recached.

**Comment by JamzTheMan** [comment]
If you need to see build.gradle or github actions:

https://github.com/JamzTheMan/TokenTool/tree/feature-jdk14

**Comment by JamzTheMan** [comment]
FWIW I tested this using WSL2 on my Windows PC and I'm seeing the same thing, missing the `bin` dir under `build/image`

```
> Task :jlink FAILED
:jlink (Thread[Execution worker for ':',5,main]) completed. Took 11.254 secs.
Closing Git repo: /home/jamz/git/TokenTool/.git

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jlink'.
> java.io.FileNotFoundException: /home/jamz/git/TokenTool/build/image/bin/TokenTool (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
10 actionable tasks: 9 executed, 1 up-to-date
jamz:~/git/TokenTool$ cd build/image/
jamz:~/git/TokenTool/build/image$ ls -al
total 24
drwxr-xr-x  5 jamz jamz 4096 Apr  4 11:25 .
drwxr-xr-x  9 jamz jamz 4096 Apr  4 11:25 ..
drwxr-xr-x  4 jamz jamz 4096 Apr  4 11:25 conf
drwxr-xr-x 23 jamz jamz 4096 Apr  4 11:25 legal
drwxr-xr-x  4 jamz jamz 4096 Apr  4 11:25 lib
-rw-r--r--  1 jamz jamz  615 Apr  4 11:25 release
jamz:~/git/TokenTool/build/image$
```

**Comment by siordache** [comment]
@JamzTheMan Thanks for reporting this issue. It was a bug in the plugin. Fixed in 2.17.5.

**Comment by JamzTheMan** [comment]
awesome! I'll test it right now and report back!

**Comment by JamzTheMan** [comment]
Looks like this fixes the issue! Thanks!
