### ISSUE TITLE
Task jlink FAILED. Error: Module XXX not found

### ISSUE THREAD

**Issue by Ealrann** [beryx/badass-jlink-plugin#13]
Hello,

I finally managed to make my project fully compatible with java 9 (all projects and dependencies are modules). `Gradle run` works from scratch. I'm able to manually make a jlink build of my project (using the jars built by gradle). Now I try to use the _badass-jlink-plugin_, but something goes wrong when I type "gradle jlink" :
`Task jlink FAILED. Error: Module XXX not found`

The module XXX (_org.lwjgl.stb_ btw, but the name is probably irrelevant here) is one external dependency of my project, but it's still a true module (contains a module-info.java and so on). [Here the stacktrace](https://pastebin.com/raw/4kH8zdCf).

I'm not sure where is the problem, since my project should already be fully compliant with java 9 (I already made a functional jlink build).

If you want to have a look on the repo, here a command to clone everything (submodules could be a bit tricky otherwise):
`git clone --single-branch -b testJLink --recursive git@github.com:Ealrann/VSand.git`

The project defining the application (and the jlink) is _org.sheepy.vulkan.sand_.

**Comment by siordache** [comment]
This is definitely a bug. I will release a fix in the next few days.
Until then, put this in your build.gradle:
```
tasks.jlink {
    doFirst {
        def jars = project.configurations['runtimeClasspath'].resolvedConfiguration.files
        copy{
            from jars.findAll {it.name.startsWith('lwjgl')}
            into jlinkJarsDir.get()
        }
    }
}
```

**Comment by Ealrann** [comment]
Works perfectly, thank you!

**Comment by siordache** [comment]
With version 2.1.8 of this plugin, the above workaround is no longer needed.

**Comment by Ealrann** [comment]
I just tested, it's working without the workaround now :). Thank you very much.
