### ISSUE TITLE
jpackage Customized Info.plist and background.tiff for mac not copied over

### ISSUE THREAD

**Issue by Siedlerchr** [beryx/badass-jlink-plugin#132]
Hi,
we are currently having problems with specifying replacement files. They are ignored, e.g. always the defaults are used.

I followed the description here: https://docs.oracle.com/en/java/javase/14/jpackage/override-jpackage-resources.html#GUID-1B718F8B-B68D-4D46-B1DB-003D7729AAB6
and we created a custom background.tiff file in the resources folder, but it's not copied over. The default is used in the final installer. We tried naming it both background.tiff and background-jabref.tiff
Similar with specifying an Info.plist

And somehow the --verbose switch is also ignored.

Do we need to pass  the options somehow in another way? 
https://github.com/JabRef/jabref/blob/master/build.gradle#L680
```

  if (OperatingSystem.current().isMacOsX()) {
            imageOptions = [
                    '--icon', "${projectDir}/src/main/resources/icons/jabref.icns",
                    '--resource-dir', "${projectDir}/buildres/mac"
            ]
            installerOptions = [
                    '--verbose',
                    '--vendor', 'JabRef',
                    '--app-version', "${project.version}",
                    '--file-associations', "${projectDir}/buildres/mac/bibtexAssociations.properties",
                    '--resource-dir', "${projectDir}/buildres/mac"
            ]
        }
```

**Comment by siordache** [comment]
@Siedlerchr To see the jpackage verbose output you also need to add the Gradle -i flag in [this line](https://github.com/JabRef/jabref/blob/42788b5f5ac3cbaf280b2858c39eda9302532e10/.github/workflows/deployment.yml#L60):
```
run: ./gradlew -i -PprojVersion="${{ steps.gitversion.outputs.AssemblySemVer }} ..."
```


After that, you will see the following message:
```
Using default package resource background_dmg.tiff [dmg background] (add JabRef-background.tiff to the resource-dir to customize).
```

So, jpackage expects to find a file named `JabRef-background.tiff` in the resource-dir.

Renaming your `JabRef-background_dmg.tiff` to `JabRef-background.tiff` should solve this issue.

**Comment by Siedlerchr** [comment]
@siordache  Thanks for the quick feedback. That works now. I will test now with the plist files as well and report back.

**Comment by Siedlerchr** [comment]
Just for reference, got it to work: Info.plist and Info.list.template seemed to be necessary
https://github.com/JabRef/jabref/tree/master/buildres/mac
