### ISSUE TITLE
A way to create a single instance of application

### ISSUE THREAD

**Issue by vewert** [beryx/badass-jlink-plugin#135]
Do you know of a way for jpackage to enforce allowing only a single instance of the application to run? I thought I remembered seeing that somewhere, but now I can't find it.

Thank-you.

**Comment by siordache** [comment]
It was possible with JNLP's [SingleInstanceListener](https://docs.oracle.com/javase/9/docs/api/javax/jnlp/SingleInstanceListener.html), but I don't think that jpackage has a similar feature.
