### ISSUE TITLE
Fail if provided jdkHome does not exist

### ISSUE THREAD

**Issue by BenKenobi57** [beryx/badass-jlink-plugin#137]
You can define the `jdkHome` for one more several target platforms like this:
```
targetPlatform("linux-x64") {
  jdkHome = "/path/to/jdk"
}
```

However, if you define an path that does not exist, jlink falls back to the jdk it is running with it seems (i.e. the current platform).
It would be nice to explicit fail if the provided jdkHome is invalid.

**Comment by siordache** [comment]
Fixed in 2.17.9

**Comment by BenKenobi57** [comment]
thanks again for the quick fix!
