### ISSUE TITLE
Feature: Ability to set ModuleInfo.Version ?

### ISSUE THREAD

**Issue by HUGIN-NSJ** [beryx/badass-jlink-plugin#138]
There is a command line option: '[javac|jar] --module-version XXX' which specifies ModuleInfo.Version.
It would be really nice to have an option for setting this version for any solution.

**Comment by siordache** [comment]
The badass-jlink-plugin is not involved in building the main application module.  This job is performed by the gradle-modules-plugin (which is also used under the hood by the org.openjfx.javafxplugin). There is an issue requesting to [add support for setting the module version](https://github.com/java9-modularity/gradle-modules-plugin/issues/124) to the gradle-modules-plugin.

However, the badass-jlink-plugin could add support for setting the version of the merged module.

**Comment by HUGIN-NSJ** [comment]
Hi siordache!
Thanks for clarifying this. I think the support for setting the version of the merged module would add great value. At least, it's a highly desired feature from my side.

**Comment by siordache** [comment]
In version 2.19.0, the plugin uses the project version or the version of the main module as default value for the version of the merged module. You can specify a custom version for the merged module as [described in the documentation](https://badass-jlink-plugin.beryx.org/releases/latest/#_mergedmodule):
```
jlink {
    mergedModule {
        version = '1.2.3'
        ...
    }
    ...
```

I also [submitted a pull request](https://github.com/java9-modularity/gradle-modules-plugin/pull/148) to the gradle-modules-plugin to allow setting the module version of the main module.

**Comment by HUGIN-NSJ** [comment]
Thanks for your assistance.
