### ISSUE TITLE
JLink script template: Run in background

### ISSUE THREAD

**Issue by Bertie2011** [beryx/badass-jlink-plugin#139]
Since I can't create mac/linux executables or installers from my windows machine, supplying users with the JRIs and their scripts is the next best option.
It's a shame that users will get to see the console window behind my GUI application though and I don't want to mess around with custom script files (since I can't test the linux and mac ones).
Perhaps you could provide a boolean option that will use scripts with commands in background instead?

For windows, simply changing `java -jar <jar>` into `start javaw -jar <jar>` will allow the script to finish (and close the console window) as soon as it launched the jar file.

**Comment by siordache** [comment]
In 2.18.0 you can use the `noConsole`property:
```
jlink {
    ...
    launcher {
        ...
        noConsole = true
    }
}
```

**Comment by Bertie2011** [comment]
Awesome!
After some trying, I got it to work in a Linux virtual machine and apparently the Linux script is always running in background (or at least not opening a console window). I saw that the noConsole property was documented as "Only has an effect on Windows", but perhaps you could add that console is always hidden on macOS and Linux for other developers on Windows who are inexperienced in the other platforms?

**Comment by siordache** [comment]
Yes, I will mention this in the documentation.
