### ISSUE TITLE
JPackage installerType="app-image", error --app-image is not valid 

### ISSUE THREAD

**Issue by dvdfmiller** [beryx/badass-jlink-plugin#140]
When I specify installerType="app-image" in jpackage I get the error that --app-image is not valid with type "app-image" though I haven't specified --app-image:

`jdk.incubator.jpackage.internal.PackagerException: Error: Option [--app-image] is not valid with type [app-image]
        at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.Arguments.validateArguments(Arguments.java:554)
        at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.Arguments.processArguments(Arguments.java:469)
        at jdk.incubator.jpackage/jdk.incubator.jpackage.main.Main.execute(Main.java:97)
        at jdk.incubator.jpackage/jdk.incubator.jpackage.main.Main.main(Main.java:51)
`

My build.gradle includes:

      jlink {    
         javaHome = '/usr/lib/jvm/jdk-11.0.6+10'
         options  = ['--strip-debug', '--compress', '2',
                          '--no-header-files', '--no-man-pages'
         ]
         imageName = ntdmImageName
         forceMerge('log4j-api')

         jpackage {        
            jpackageHome = '/usr/lib/jvm/jdk-14.0.1+7'
            launcher {
              jvmArgs = ["-splash:$ntdmSplash"]
            }
            installerOptions = [
                '--description', ntdmAppName,
                '--app-version', ntdmVersion,
                '--copyright',   ntdmAppCopyright,
                '--verbose',
                '--license-file', './distribution/licence.txt'
            ]        
            installerType = "app-image"
         }
      }

**Comment by siordache** [comment]
The plugin runs jpackage twice, using the approach [described here](https://docs.oracle.com/en/java/javase/14/jpackage/image-and-runtime-modifications.html#GUID-70F25F63-DE4C-4DC0-83D5-76EB5C55BEF0).
If you specify `installerType="app-image"`, the plugin will execute on the second run something like this:
```
jpackage --type app-image --app-image ...
```
The above command is not valid. `app-image` is not a proper installer type, but a special value that tells jpackage to NOT generate an installer.

However, if for some reason you really want to specify `installerType="app-image"`, you need to skip the second run of the jpackage:
```
jpackage {
    ...
    installerType = "app-image"
    skipInstaller = true
}
```

**Comment by dvdfmiller** [comment]
Hi Serban,
That's perfect - I confirm it works. Thanks for your prompt reply.

I want jpackage to create the app-image only without creating an install package, as I take this app-image (with amendments) on linux to feed into NSIS to create an installer for windows.

Many thanks
David

**Comment by siordache** [comment]
In this case you don't need to specify an installerType. Just set `skipInstaller = true`.

**Comment by dvdfmiller** [comment]
Thank you. Very helpful.
best regards
David
