### ISSUE TITLE
[Question] gradle 6.4.1, module not found error

### ISSUE THREAD

**Issue by ceyhunn** [beryx/badass-jlink-plugin#141]
Hi @siordache ,
I run `./gradlew -i jlink`, and fixed issues.
Only problem is that `Couldn't find module-info.java in src/main/java, build/generated-src/jooq/main`
Then I created module-info.java like for example: 
```
module my.module {
      requires my.dependency
      .....
}
```
My.dependency is a non modular dependency. `./gradlew build` gives error: `module not found my.dependency`. Also I don't know how to create `module-info.java` for `build/generated-src/jooq/main`, it is generated during build process.

I use gradle 6.4.1, java 11, jlink latest version, java-library gradle plugin

**Comment by siordache** [comment]
Do you get the same error when executing `./gradlew build`? If yes, then it's not a badass-jlink-plugin issue.

However, I might be able to help if you create a [SSCCE](http://sscce.org/) on GitHub.

**Comment by ceyhunn** [comment]
Sorry for late answer, I created [demo app](https://github.com/ceyhunn/demo). I don't know why this doesn't work. It would be pleasant for me, if you help me.

**Comment by siordache** [comment]
Using org.beryx.jlink to create a custom runtime image for a spring-boot application is not straightforward, There are quite a few things to be configured in build.gradle. I submitted a [pull request](https://github.com/ceyhunn/demo/pull/1) with the necessary changes.

An easier way to create the custom runtime image is to **not** modularize your application. In this case you need to use the [org.beryx.runtime plugin](https://github.com/beryx/badass-runtime-plugin/). If you want to take this approach, you can find the necessary changes in [this branch](https://github.com/siordache-forks/demo/tree/badass-runtime).

**Comment by ceyhunn** [comment]
@siordache, thank you so much for help and explaination. However, I have some questions:
1. You removed application-development.properties, doesn't this plugin support spring profiles? If I create configuration bean classes for each profile, does this work? I just added this for testing spring profiles, because I have a lot of this in my projects.
2.  Why `demo.main/com.example.demo.Application` main class doesn't work?

**Comment by ceyhunn** [comment]
I have tested your merge, but Initializer class doesn't work. I can't see logs like in `./gradlew run `

**Comment by siordache** [comment]
> I have tested your merge, but Initializer class doesn't work. I can't see logs like in `./gradlew run `

You're right. Spring's ClassPathScanner doesn't find the Initializer. We need to put the application classes on the classpath. We also need to add a few `--add-exports` and `--add-opens` options to let Spring inspect these classes. I submitted a [new pull request](https://github.com/ceyhunn/demo/pull/2) with the necessary changes.

> 1. You removed application-development.properties, doesn't this plugin support spring profiles? If I create configuration bean classes for each profile, does this work? I just added this for testing spring profiles, because I have a lot of this in my projects.

Spring profiles are supported. I configured the `development` profile in the new PR:
```
launcher {
    jvmArgs = [
        ...
        '-Dspring.profiles.active=development',
        ....
    ]
}
```

> 2. Why demo.main/com.example.demo.Application main class doesn't work?

Since Gradle 6.4, demo.main/com.example.demo.Application no longer works. The preferred way is to use the properties [`mainClass` and `mainModule`](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.JavaApplication.html#org.gradle.api.plugins.JavaApplication:mainClass):
```
application {
    mainModule = 'demo.main'
    mainClass = 'com.example.demo.DemoApplication'
}
```

**Comment by ceyhunn** [comment]
Not worked, seems like classes with  @Service, @Repository, @Component annotation isn't recognized by spring.

**Comment by siordache** [comment]
What didn't work? On my machine, the application successfully creates and deletes an entry in the `example` table. I added the following jvmArgs:
```
-Dlogging.level.org.springframework=DEBUG -Dlogging.level.org.jooq=TRACE
```

and that's what the application writes on the console now:

```
2020-06-01 10:48:19.450 DEBUG 78408 --- [           main] org.jooq.tools.LoggerListener            : Executing query          : insert into "public"."EXAMPLE" ("ID", "NAME") values (?, ?)
2020-06-01 10:48:19.451 DEBUG 78408 --- [           main] org.jooq.tools.LoggerListener            : -> with bind values      : insert into "public"."EXAMPLE" ("ID", "NAME") values ('key', 'name')
2020-06-01 10:48:19.463 DEBUG 78408 --- [           main] o.s.jdbc.datasource.DataSourceUtils      : Fetching JDBC Connection from DataSource
2020-06-01 10:48:19.468 TRACE 78408 --- [           main] org.jooq.impl.DefaultBinding             : Binding variable 1       : key (class java.lang.String)
2020-06-01 10:48:19.469 TRACE 78408 --- [           main] org.jooq.impl.DefaultBinding             : Binding variable 2       : name (class java.lang.String)
2020-06-01 10:48:19.485 DEBUG 78408 --- [           main] org.jooq.tools.LoggerListener            : Affected row(s)          : 1
Example saved
2020-06-01 10:48:19.491 DEBUG 78408 --- [           main] org.jooq.tools.LoggerListener            : Executing query          : delete from "public"."EXAMPLE" where "public"."EXAMPLE"."ID" = ?
2020-06-01 10:48:19.492 DEBUG 78408 --- [           main] org.jooq.tools.LoggerListener            : -> with bind values      : delete from "public"."EXAMPLE" where "public"."EXAMPLE"."ID" = 'key'
2020-06-01 10:48:19.493 DEBUG 78408 --- [           main] o.s.jdbc.datasource.DataSourceUtils      : Fetching JDBC Connection from DataSource
2020-06-01 10:48:19.493 TRACE 78408 --- [           main] org.jooq.impl.DefaultBinding             : Binding variable 1       : key (class java.lang.String)
2020-06-01 10:48:19.496 DEBUG 78408 --- [           main] org.jooq.tools.LoggerListener            : Affected row(s)          : 1
Example deleted
```

That's exactly what I expected. Is there something else that the application should do?

**Comment by ceyhunn** [comment]
@siordache , Sorry for wasting your time, but in my execution I can't see `Example saved`, `Example deleted` logs.
[logs.txt](https://github.com/beryx/badass-jlink-plugin/files/4712208/logs.txt)

**Comment by ceyhunn** [comment]
I saw the problem. Classpath `../app` is relative path. Only works if workdir is bin folder. Thank you very much for all, especially taking time for me.

**Comment by siordache** [comment]
Oh, sorry. Put this in jvmArgs:
```
jvmArgs = [
    '-cp', '{{BIN_DIR}}/../app',
    ...
]
```

The plugin replaces `{{BIN_DIR}}` with the path to the `bin` directory. This way, you can start the application from any directory.

**Comment by ceyhunn** [comment]
Hi @siordache , I want to dockerize the app, but it depends on bash script, is it possible to docker run this from scratch base image?

**Comment by siordache** [comment]
I don't think it's possible to start from a scratch base image (unless you're willing to put a lot of effort into it).  You still need a minimal Linux distribution and some implementation of the C standard library (such as glibc or musl) on your container.

I used [panga/alpine](https://hub.docker.com/r/panga/alpine) as base image for some of my java projects. It is a small image. It doesn't contain bash, but you don't need it, because the start script depends on sh and not on bash. See examples [here](https://github.com/beryx/talk-javazone-2019/blob/master/prj-6/Dockerfile) and [here](https://github.com/beryx/talk-javazone-2019/blob/master/prj-6/Dockerfile-stripped).
