### ISSUE TITLE
Unexplained NullPointerException in JlinkTask when no main class is specified

### ISSUE THREAD

**Issue by jgcodes2020** [beryx/badass-jlink-plugin#146]
[Here's what came out of gradlew jlink --stacktrace](https://gist.github.com/jgcodes2020/3bbf347a769c9cd26cd46da213f77313)

# What happened?
I am building a native installer for [this project](https://github.com/jgcodes2020/JFX-Analog-Clock). It's a simple analog clock. It runs fine in IntelliJ 2020.1.2. However, I noticed that the plugin throws a NullPointerException. I ended up solving the problem by specifying a main class.
# How can it be fixed?
Use `Objects.requireNonNull()` and a simple error message.

**Comment by siordache** [comment]
Thanks for reporting this issue! Fixed in 2.21.2.
