### ISSUE TITLE
Support for java preview features

### ISSUE THREAD

**Issue by thekalinga** [beryx/badass-jlink-plugin#150]
Is there a way to add support for java preview features?

i.e like adding `--enable-preview` to jlink vm options?

I built the image using the following options

```groovy
jlink {
    addOptions("--strip-debug", "--compress", "--no-header-files", "--no-man-pages", "--enable-preview")
    launcher {
        name = "App"
        args = listOf("--enable-preview")
        jvmArgs = listOf("JLINK_VM_OPTIONS=--enable-preview")
    }
}
```

But I get an error saying

`Preview features are not enabled for com/acme/Demo (class file version 58.65535). Try running with '--enable-preview'`

**Comment by siordache** [comment]
I put up an example that uses [text blocks](https://github.com/beryx-gist/badass-jlink-example/blob/2178fe59d6fc7b779f9353b5d9f43f64a6e06684/src/main/java/org/beryx/modular/hello/Hello.java#L10-L14) on the [preview-features branch](https://github.com/beryx-gist/badass-jlink-example/tree/preview-features) of badass-jlink-example.
You need to also [enable preview features for the JavaCompile tasks](https://github.com/beryx-gist/badass-jlink-example/blob/2178fe59d6fc7b779f9353b5d9f43f64a6e06684/build.gradle#L32-L34):
```
tasks.withType(JavaCompile) {
    options.compilerArgs += "--enable-preview"
}
```

**Comment by thekalinga** [comment]
Thank you. After I added `--enable-preview` in multiple places based on your example, it is working now.
