### ISSUE TITLE
one package, multiple launchers, but only one require win-console, is there a way to do that?

### ISSUE THREAD

**Issue by optyfr** [beryx/badass-jlink-plugin#152]
Seems that there is only one general imageOptions for --win-console, so that it is applied to all declared launchers, but I wonder if it could be possible to add the possiblity to specify --win-console only for one (secondary)Launcher and not the others?

**Comment by siordache** [comment]
In [2.22.0](https://github.com/beryx/badass-jlink-plugin/releases/tag/v2.22.0) I added the `winConsole` property to `secondaryLauncher`:

```
jlink {
    ...
    secondaryLauncher {
        ...
        winConsole = false
    }
    ...
}
```

See [the documentation](https://badass-jlink-plugin.beryx.org/releases/latest/#_secondarylauncher) for more info.

**Comment by optyfr** [comment]
This worked perfectly, thank you!
