### ISSUE TITLE
'.deb' type installer error

### ISSUE THREAD

**Issue by UltraBurstXD** [beryx/badass-jlink-plugin#155]
I'm using a Debian based OS, Ubuntu 20.04, so I choose deb installer type instead rpm because I was getting: `Error: Invalid or unsupported type: [rpm]`
Even so it fires: `java.io.IOException: Command [fakeroot, dpkg-deb, -b, /tmp/jdk.incubator.jpackage9938668687627305745/images, /home/ultraXD/NetBeansProjects/SimpleFX/build/jpackage/simplefx_unspecified-1_amd64.deb] exited with 2 code`

pls, help!

**Comment by siordache** [comment]
You probably need to set the project version in your build.gradle:
```
version = "1.0.0"
```

**Comment by UltraBurstXD** [comment]
Humm... Thanks!
