### ISSUE TITLE
Kotlin samples package incorrectly with newer dependencies

### ISSUE THREAD

**Issue by MariusVolkhart** [beryx/badass-jlink-plugin#156]
I tried to update the JavaFX Kotlin sample to the latest version of Kotlin (1.4.10), a newer version of Gradle (6.6.1), and the latest version of the jlink plugin (2.22.1). Compilation succeeds, but the program fails at runtime with the following message:
```
badass-jlink-example-kotlin-javafx$ ./build/image/bin/hello                                                                   
Error: Could not find or load main class test.kotlin/org.beryx.jlink.test.kotlin.JavaFX in module test.kotlin
```

I assume Gradle or Kotlin changed something and the following lines no longer work the way they did in Gradle 5/Kotlin 1.3.10:
```kotlin
val compileKotlin: KotlinCompile by tasks
val compileJava: JavaCompile by tasks
compileJava.destinationDir = compileKotlin.destinationDir
```

I've drafted the changes here, but since the failure only occurs at runtime, I've not submitted as a full PR.
https://github.com/beryx-gist/badass-jlink-example-kotlin-javafx/pull/3

**Comment by MariusVolkhart** [comment]
It seems to work with Gradle 6.3, but not with 6.4.1, so the change was probably in Gradle at that version number.

**Comment by siordache** [comment]
Thanks for the PR! 
In recent Gradle versions, the `mainClassName` parameter should be replaced with [mainModule and mainClass](https://docs.gradle.org/current/userguide/application_plugin.html#sec:application_modular). I requested these changes in your PR.

**Comment by MariusVolkhart** [comment]
That change fixed the problem. I thought I tried that before, but it must have been in my own (not sample) project. Thanks for the help, and the plugin!
