### ISSUE TITLE
Kotlin with Non-Modular dependencies can build but not run

### ISSUE THREAD

**Issue by SergeySave** [beryx/badass-jlink-plugin#171]
I was trying to get this plugin working on a project of mine, but while I got it to build the jlink image, it would fail to run. I then reduced the code base to the following minimal example: [https://github.com/SergeySave/JLinkTest](https://github.com/SergeySave/JLinkTest). 

Essentially this codebase has two dependencies: the Kotlin standard library and [https://github.com/MicroUtils/kotlin-logging](https://github.com/MicroUtils/kotlin-logging). By using [these lines](https://github.com/SergeySave/JLinkTest/blob/master/build.gradle#L29-L37) it is possible to get it to build (and run using the gradle application run task) properly. However, when I run the jlink task and then try to run the image I get the following error:

```
java.lang.LayerInstantiationException: Package kotlin.experimental in both module kotlin.stdlib and module com.sergeysav.merged.module
        at java.base/jdk.internal.module.ModuleBootstrap.checkSplitPackages(Unknown Source)
        at java.base/jdk.internal.module.ModuleBootstrap.boot(Unknown Source)
        at java.base/java.lang.ClassLoader.initializeClassLoaders(Unknown Source)
        at java.base/java.lang.Thread.initialize(Unknown Source)
        at java.base/java.lang.Thread.<init>(Unknown Source)
```

Note: each time I run it, it outputs a different package which is duplicated between kotlin.stdlib and the merged module.

Additionally If I look inside of the merged module jar in `build/jlinkbase/jlinkjars` the kotlin packages are full of `*.kotlin_metadata` files.

Is this something that I am doing wrong with my `build.gradle` file or is this an issue with the jlink plugin?

**Comment by siordache** [comment]
See [this issue](https://github.com/beryx/badass-jlink-plugin/issues/165) for an explanation why `forceMerge "kotlin"` is required.

**Comment by SergeySave** [comment]
Thanks that worked!
