### ISSUE TITLE
Gradle 7.0 compatibility issues

### ISSUE THREAD

**Issue by nemphys** [beryx/badass-jlink-plugin#175]
I have been seeing some warnings regarding gradle 7.0 deprecations all this time, but today I tried building with Gradle 7.0 milestone 3 (since I am testing Java 16) and the output is:

* What went wrong:
Some problems were found with the configuration of task ':common:generateModuleInfo' (type 'GenerateModuleInfoTask').
  - Type 'GenerateModuleInfoTask' property 'outputDirectory' is annotated with @PathSensitive but that is not allowed for 'OutputDirectory' properties.

    Reason: This modifier is used in conjunction with a property of type 'OutputDirectory' but this doesn't have semantics.

    Possible solution: Remove the '@PathSensitive' annotation.

    Please refer to https://docs.gradle.org/7.0-milestone-3/userguide/validation_problems.html#incompatible_annotations for more details about this problem.
  - Type 'GenerateModuleInfoTask' property 'workingDirectory' is annotated with @PathSensitive but that is not allowed for 'OutputDirectory' properties.

    Reason: This modifier is used in conjunction with a property of type 'OutputDirectory' but this doesn't have semantics.

    Possible solution: Remove the '@PathSensitive' annotation.

    Please refer to https://docs.gradle.org/7.0-milestone-3/userguide/validation_problems.html#incompatible_annotations for more details about this problem.

**Comment by siordache** [comment]
This is about the [moditect-gradle-plugin](https://github.com/moditect/moditect-gradle-plugin), I guess.

I [removed these annotations](https://github.com/moditect/moditect-gradle-plugin/commit/35a54fa3cfd8946ef0728f7d1943548119b64aed#diff-e4dee8251d765faf3fd1c63cde40e88909793b2e0f471df21ea383d5fe690bc6) a few months ago. Do you use the 1.0.0-rc3 version?

**Comment by nemphys** [comment]
Sorry, you're right, didn't notice the new version.
