### ISSUE TITLE
JPackage config only conains app.mainmodule and [JavaOptions] 

### ISSUE THREAD

**Issue by grigala** [beryx/badass-jlink-plugin#185]
Hi, 

I used to have a lot more information in my `app.cfg` file:
```
[Application]
app.name=AppName
app.version=1.0.0
app.runtime=$ROOTDIR\runtime
app.identifier=
app.classpath=
app.mainmodule=...Launcher
```

But with the newest plugin and JDK 15 based jpackage I only get a single `app.mainmodule` entry in the file.

Is there anything I can do to get the information(the version is most important) back to `.cfg` file again?

P.S.  When I call jpackage using comand line and pass arguments like `--app-version 1.0.0` I do get this information written into the `.cfg` file like `app.version=1.0.0`, is there anything fundamentally different with the task itself?

**Comment by siordache** [comment]
Did you call the JDK15 jpackage when using the command line? Or the JDK14 jpackage? I get this information written in the `.cfg` file only when using the JDK14 version. 

It seems that the JDK15 jpackage no longer writes this information (see [this change](https://github.com/openjdk/jdk/commit/28d2cdf99aa4fbced870f6039274ed039df6f76d#diff-d7468066d83d9f452a4cd0eb2affa2f704c20899300030c0d5041a7507dc53c3L98-L101) from June 2020). Instead, you should find the version in the `JavaOptions` section (see [this change](https://github.com/openjdk/jdk/commit/9e6782d24b93a5e66fa0387223050c016ab47900#diff-6d12eee38b5483cb03f67c009c63ab980ecfea39fbd653ed351b1b2f5957a5f1R89-R93) from August 2020).
```
[JavaOptions]
java-options=-Djpackage.app-version=1.2.3
```

**Comment by grigala** [comment]
Thanks for the reply @siordache, you are right just double-checked, and apparently I was calling JDK14 based jpackage.

In the meantime, I created a Gradle task to manually write it in the file which works as a workaround.

I wonder why did they remove it though, I don't think it had anything to do with the [issue](https://bugs.openjdk.java.net/browse/JDK-8246627). 🤔

**Comment by grigala** [comment]
It's strange I don't get that `java-options=-Djpackage.app-version=1.2.3` written in the file either. 

Does there need to be anything else than `appVersion = ver` inside the `jpackage` task to get it written into the config?

**Comment by siordache** [comment]
No, there shouldn't be anything else. If you run gradle with the `-i` option, you can see the `jpackage` commands generated by the plugin. Check if `--app-version` is really there.

**Comment by grigala** [comment]
Yes it's there during jpackage command line call:
![image](https://user-images.githubusercontent.com/2084794/118968318-0f588c80-b96c-11eb-8379-9426aa4447d2.png)

Maybe I should have mentioned this before, but there is another file being created inside `/app` dir called `.jpackage.xml` and this thing has both version and launcher name in it:
```xml

<?xml version="1.0" ?>
<jpackage-state version="15.0.2" platform="windows">
  <app-version>2.9.0</app-version>
  <main-launcher>App Name</main-launcher></jpackage-state>
  ```

**Comment by vewert** [comment]
I checked the output folder of a build it did a few weeks ago, using this plugin, and jpackage16 and the .cfg folder does contain:

```
[JavaOptions]
java-options=-Djpackage.app-version=4.0.0.0
```

Maybe this is a problem jpackage15?

**Comment by siordache** [comment]
I think the best thing to do is to ask on the [core-libs-dev mail list](https://mail.openjdk.java.net/pipermail/core-libs-dev/) if there is a reliable way to get the version information.
