### ISSUE TITLE
Cannot generate merged module

### ISSUE THREAD

**Issue by palexdev** [beryx/badass-jlink-plugin#187]
Hello, I'm having an issue generating a jlink zip with my project.
My project ([MaterialFX](https://github.com/palexdev/MaterialFX)) has two modules, one module is the actual project and the other one is the demo module.
I need to add a dependency to the generated jar, so I modified the jar task like this:
```
jar {
    manifest {
        attributes(
                'Bundle-Name': project.name,
                'Bundle-Description': "Material controls for JavaFX",
                'Bundle-SymbolicName': 'io.github.palexdev',
                'Export-Package': 'io.github.palexdev.materialfx.*, io.github.palexdev.materialfx.demo.*'
        )
    }

    from {configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
}

```

This adds the dependency and seems to work good but when I try to generate a jlink image I get this error:
`Module MaterialFX contains package org.reactfx.util, module MaterialFX.merged.module exports package org.reactfx.util to MaterialFX
`
I don't know how to fix it, can you help me?

**Comment by siordache** [comment]
Can you push the code that allows reproducing this error?

**Comment by palexdev** [comment]
> Can you push the code that allows reproducing this error?

Here it is: [MaterialFX](https://github.com/palexdev/MaterialFX/tree/jlink-issue), I created a temporary branch
Thanks!

**Comment by siordache** [comment]
Thanks! The easiest way is to make it work is to [force-merge](https://github.com/palexdev/MaterialFX/blob/c85024230f31b1205958eee861f1f5145877d723/demo/build.gradle#L41) `materialfx`:
```
jlink {
    ...
    forceMerge('log4j-api', 'materialfx')
}
```

**Comment by palexdev** [comment]
Thank you very much for the quick support!! Closing the issue
