### ISSUE TITLE
Jackson2 createMergedModule cannot derive uses clause

### ISSUE THREAD

**Issue by GarryMoveOut** [beryx/badass-jlink-plugin#19]
I have problem with adding Jackson2 Databind dependency to my custom runtime image. Project compile successful but application get exception while running. To reproduce problem I cloned example openjfx with log4j added new dependency to build.gradle: 
`compile group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.9.8'`
added require to module-info:
`requires com.fasterxml.jackson.databind;`
to start() added few lines with mapper:
```
ObjectMapper mapper = new ObjectMapper();
        String jsonInString = "{\"name\":\"user1\",\"age\":20}";
        try {
            User user = mapper.readValue(jsonInString, User.class); //User is simple POJO
        } catch (IOException e) {
            LogManager.getLogger().log(Level.ERROR, e);
        }
```
And when I run task jlink with gradle5 I get:

> Executing task 'jlink'...
> 
> 
> > Configure project :
> Found module name 'hellofx'
> 
> > Task :compileJava
> > Task :processResources
> > Task :classes
> > Task :jar
> > Task :prepareMergedJarsDir
> 
> > Task :createMergedModule
> Cannot derive uses clause from service loader invocation in: com/fasterxml/jackson/databind/ObjectMapper$2.run().
> Cannot derive uses clause from service loader invocation in: com/fasterxml/jackson/databind/ObjectMapper.secureGetServiceLoader().
> 
> > Task :createDelegatingModules
> > Task :prepareModulesDir
> > Task :jlink
> 
> BUILD SUCCESSFUL in 36s
> 8 actionable tasks: 8 executed

But when I run app I get:

> Exception in Application start method
> java.lang.reflect.InvocationTargetException
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.base/java.lang.reflect.Method.invoke(Unknown Source)
>         at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
>         at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.base/java.lang.reflect.Method.invoke(Unknown Source)
>         at java.base/sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
> Caused by: java.lang.RuntimeException: Exception in Application start method
>         at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
>         at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
>         at java.base/java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make org.openjfx.User() accessible: module hellofx does not "opens org.openjfx" to module hellofx.merged.module
>         at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
>         at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
>         at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Unknown Source)
>         at java.base/java.lang.reflect.Constructor.setAccessible(Unknown Source)
>         at hellofx.merged.module/com.fasterxml.jackson.databind.util.ClassUtil.checkAndFixAccess(Unknown Source)
>         at hellofx.merged.module/com.fasterxml.jackson.databind.deser.impl.CreatorCollector._fixAccess(Unknown Source)
>         at hellofx.merged.module/com.fasterxml.jackson.databind.deser.impl.CreatorCollector.setDefaultCreator(Unknown Source)
>         at hellofx.merged.module/com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._addDeserializerConstructors(Unknown Source)
>         at hellofx.merged.module/com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(Unknown Source)
>         at hellofx.merged.module/com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(Unknown Source)
>         at hellofx.merged.module/com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(Unknown Source)
>         at hellofx.merged.module/com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(Unknown Source)
>         at hellofx.merged.module/com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(Unknown Source)
>         at hellofx.merged.module/com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(Unknown Source)
>         at hellofx.merged.module/com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(Unknown Source)
>         at hellofx.merged.module/com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(Unknown Source)
>         at hellofx.merged.module/com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(Unknown Source)
>         at hellofx.merged.module/com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(Unknown Source)
>         at hellofx.merged.module/com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(Unknown Source)
>         at hellofx.merged.module/com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(Unknown Source)
>         at hellofx.merged.module/com.fasterxml.jackson.databind.ObjectMapper.readValue(Unknown Source)
>         at hellofx/org.openjfx.HelloFX.start(Unknown Source)
>         at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
>         at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
>         at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
>         at java.base/java.security.AccessController.doPrivileged(Native Method)
>         at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
>         at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
>         at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
>         at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
>         ... 1 more
> 

Besides. I discovered that adding non modular dependencies to modular project is very painful. Is there a repository or list of popular dependencies/libraries which can be easily added to modular project?

**Comment by siordache** [comment]
Try making the `hellofx` module open:

```
open module hellofx {
    requires javafx.controls;
    requires org.apache.logging.log4j;
    requires com.fasterxml.jackson.databind;

    exports org.openjfx;
}
```

I don't know if there is such a list of popular libraries.
Some applications cannot be easily modularized, but sometimes you don't really have to modularize them. If you only need to create a custom runtime image, then you can leave your application non-modularized and use the [badass-runtime-plugin](https://github.com/beryx/badass-runtime-plugin).

**Comment by GarryMoveOut** [comment]
Both solutions are working. I think you are genius :) thank you

**Comment by siordache** [comment]
Thanks! 😄
