### ISSUE TITLE
How to handle runtime-only dependencies on JDK modules?

### ISSUE THREAD

**Issue by markslater** [beryx/badass-jlink-plugin#191]
What is the preferred way of making the plugin aware of JDK dependencies that only apply at runtime?  I have [an example project](https://github.com/markslater/jlink-query) with an implicit transitive dependency on a JDK module: `org.eclipse.jetty:jetty-server:11.0.6` executes `Class.forName("java.lang.management.ManagementFactory", true, cl)`.

My full Gradle file is:
```kotlin
plugins {
    java
    id("org.beryx.jlink") version "2.24.0"
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(16))
    }
}

dependencies {
    implementation(group = "org.eclipse.jetty", name = "jetty-server", version = "11.0.6")
    runtimeOnly(group="org.slf4j", name= "slf4j-nop", version = "2.0.0-alpha1")
}

application {
    mainClass.set("com.example.Example")
    mainModule.set("com.example")
}

jlink {
    options.set(listOf("--strip-debug", "--compress", "2", "--no-header-files", "--no-man-pages"))
    forceMerge("slf4j")
}
```

and my `module-info` is:
```java
module com.example {
    requires org.eclipse.jetty.server;
}
```

This fails at runtime (e.g. `./gradlew jlink && build/image/bin/example`), apparently because the plugin doesn't include `java.lang.management.ManagementFactory` isn't in the image it generates.

I can [fix the problem](https://github.com/markslater/jlink-query/commit/b4803776ea5924eed445013a886417ecc2733ed5) by adding a module dependency on `java.management`, but this feels wrong: my module doesn't have a real first-order dependency on `java.management`, and ideally the compiler should tell me if I inadvertently introduce such a dependency.
I tried [adding it to a `mergedModule` block](https://github.com/markslater/jlink-query/commit/0f8e2992429da474e9275bce425bb009a50df824), but that doesn't fix it - I suspect I have misunderstood the documentation on this.

Is there a better way of including the module than adding it to the `module-info`?  Alternatively, is this actually an issue with the Jetty project needing to specify a transitive dependency on `java.management` in *their* `module-info`?

Apologies if this is a JPMS 101 level question.

**Comment by siordache** [comment]
That's strange. On my machine, I no longer get the error when [adding java.management to mergedModule](https://github.com/markslater/jlink-query/commit/0f8e2992429da474e9275bce425bb009a50df824).

Do you still get the error even when using `requiresTransitive`?

```
jlink {
    ...
    mergedModule {
        additive = true
        requiresTransitive("java.management")
    }
}
```

**Comment by markslater** [comment]
Apologies - I merged in another change that made the problem go away, and failed to check properly before submitting the issue.

[Removing `forceMerge("slf4j")`](https://github.com/markslater/jlink-query/commit/6688462f756c23f473c8cf22b699e6b55912b6ac) exposes the issue.

**Comment by siordache** [comment]
Yup, it was a bug. It should work now with 2.24.1.

**Comment by markslater** [comment]
Looks good now. Thanks for the fast turnaround!
