### ISSUE TITLE
jlink launcher fails if mainClassName contains moduleName

### ISSUE THREAD

**Issue by jperedadnr** [beryx/badass-jlink-plugin#195]
Running a JavaFX gradle project with Gradlew 7.0.1 on Windows with JDK16:

```
plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.10'
    id 'org.beryx.jlink' version '2.24.0'
}

repositories {
    mavenCentral()
}

javafx {
    version = "17-ea+16"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

mainClassName = "mm/aa.bb.Main"

jlink {
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    launcher {
        name = 'sample'
    }
}
```

`gradlew run` works fine
`gradlew jlink` works fine
`build\image\bin\java -m mm/aa.bb.Main` works fine
`build/image/bin/sample` fails:
```
build\image\bin\sample
Error: Could not find or load main class mm/aa.bb.Main in module mm
```

If we check the launcher sample.bat, the error is clear, as the module name is duplicated:
```
... -m mm/mm/aa.bb.Main  %* & popd
```
because `${moduleName}/${mainClassName}` is applied:
https://github.com/beryx/badass-jlink-plugin/blob/master/src/main/resources/windowsScriptTemplate.txt#L11

However, removing the module name from the build file:

```
mainClassName = "aa.bb.Main"
```
fails when running jlink.

As far as I can see, all the samples linked for the plugin use `mainClassName  = mm/aa.bb.cc`. 

I take that the correct way now is?

```
application {
    mainModule = "mm"
    mainClass = "aa.bb.Main"
}
```
?

**Comment by siordache** [comment]
Yes, that's the correct way now. I need to update the samples.

**Comment by jperedadnr** [comment]
Okay, thanks for your quick reply!
