### ISSUE TITLE
jlink build error with dependency apache-poi

### ISSUE THREAD

**Issue by dvdfmiller** [beryx/badass-jlink-plugin#20]
Issuing ./gradlew jlink with the apache-poi dependency:
`compile ('org.apache.poi:poi:4.0.1') `

**I get this error:**
`Cannot derive uses clause from service loader invocation in: org/apache/commons/compress/utils/ServiceLoaderIterator.<init>().
/home/user/workspace/TestGluonApplication/build/jlinkbase/tmpjars/TestGluonApplication.merged.module/module-info.java:191: error: package is empty or does not exist: org.apache.poi.poifs
    exports org.apache.poi.poifs;
`

This issue is the same as the closed issue: Error when a dependency has no classes in a package #7

--------------------------------------------------------------------------------------------------------------------------------
**My environment:**
_host Ubuntu 18.04.1
gradle 5.0
openjdk 11.0.1
Javafx 11.0.1_

--------------------------------------------------------------------------------------------------------------------------------
**here's my build.gradle:**
plugins {	
    id 'org.openjfx.javafxplugin' version '0.0.5'
    id 'org.beryx.jlink' version '2.1.9'     
}

repositories {
    jcenter()
    mavenCentral()		
}

mainClassName = 'testgluonapplication/com.gluonapplication.GluonApplication'

dependencies {
	compile ('org.apache.poi:poi:4.0.1') 	
	compile ('org.apache.poi:poi-ooxml:4.0.1')
}

javafx {
		version = "11.0.1"
		modules = [ 'javafx.controls',					
					'javafx.fxml',						
					'javafx.web'					
				  ]
}

compileJava {
    doFirst {
        options.compilerArgs = [
                '--module-path', classpath.asPath,					
                '--add-modules', 'javafx.controls',
                '--add-modules', 'javafx.fxml',					
                '--add-modules', 'javafx.web'                
        ]
    }
}

jlink {
	javaHome = '/usr/lib/jvm/jdk-11.0.1+13'
	options = ['--strip-debug', '--compress', '2',
			 '--no-header-files', '--no-man-pages'			 
			 ]
    addExtraDependencies("javafx")    
	launcher {
		name = 'testgluonapplication'
	}	
}

--------------------------------------------------------------------------------------------------------------------------------
**Here's my module-info.java:**
module testgluonapplication { 

requires javafx.controls;
requires javafx.fxml;
requires javafx.web;

requires poi;
requires poi.ooxml; 

exports com.gluonapplication;      
}

--------------------------------------------------------------------------------------------------------------------------------
**Here's my javafx code:**
package com.gluonapplication;

import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class GluonApplication extends Application {    

	HSSFWorkbook workbookH = null;
	XSSFWorkbook workbookX = null;
	
	@Override
	public void start(Stage stage) {		
		StackPane root = new StackPane(
				new Label("Hello JavaFX World! <<<<<<<<<<<<<<"));			
		stage.setScene(new Scene(root));
		stage.show();
       } 
}
--------------------------------------------------------------------------------------------------------------------------------

The classes and folders for org.apache.poi.poifs are copied OK in my build/jlinkbase folders and so the poifs package is not empty and does exist, contrary to the error message. Tried forceMerge 'poi' but this didn't help. Any thoughts what to try?

**Comment by siordache** [comment]
Thanks for reporting. Fixed in 2.3.1. 
Try it with the following `build.gradle`:

```
plugins {
    id 'org.openjfx.javafxplugin' version '0.0.5'
    id 'org.beryx.jlink' version '2.3.1'
}

repositories {
    jcenter()
    mavenCentral()
}

mainClassName = 'testgluonapplication/com.gluonapplication.GluonApplication'

dependencies {
    compile('org.apache.poi:poi:4.0.1')
    compile('org.apache.poi:poi-ooxml:4.0.1')
}

javafx {
    version = "11.0.1"
    modules = ['javafx.controls',
               'javafx.fxml',
               'javafx.web'
    ]
}

jlink {
    javaHome = '/usr/lib/jvm/jdk-11.0.1+13'
    options = ['--strip-debug', '--compress', '2',
               '--no-header-files', '--no-man-pages'
    ]
    launcher {
        name = 'testgluonapplication'
    }
}

```

**Comment by dvdfmiller** [comment]
Yes I confirm that's worked. Many thanks for all your help and prompt response - 1st class support!

**Comment by siordache** [comment]
Put the following line:
```
addExtraDependencies("javafx")
```
in the `jlink` block.
