### ISSUE TITLE
Assertion GDK_IS_X11_DISPLAY failed on Linux

### ISSUE THREAD

**Issue by elifarley** [beryx/badass-jlink-plugin#22]
When I try to execute the `hello` script from an example ([like this](beryx-gist/badass-jlink-example-kotlin-tornadofx)) on Arch Linux, I get this error:

```
(java:4699): Gdk-CRITICAL **: 15:21:54.654: gdk_x11_display_set_window_scale: assertion 'GDK_IS_X11_DISPLAY (display)' failed 
# 
# A fatal error has been detected by the Java Runtime Environment: 
# 
# SIGSEGV (0xb) at pc=0x00007f015836642b, pid=4699, tid=4747 
```

See [this openjfx bug report](https://bugs.openjdk.java.net/browse/JDK-8215104)

**Comment by siordache** [comment]
It's an openjfx bug. Try the proposed workarounds.

**Comment by elifarley** [comment]
Fair :)
