### ISSUE TITLE
Launcher scripts reference non-existant directory: "%~dp0/../app"

### ISSUE THREAD

**Issue by transentia** [beryx/badass-jlink-plugin#222]
EG: https://github.com/beryx/badass-jlink-plugin/blob/master/src/main/resources/windowsScriptTemplateJavaw.txt
(but for all the template files)

```
pushd %DIR% & start "${moduleName}" %JAVA_EXEC% %CDS_JVM_OPTS% ${jvmArgs} -p "%~dp0/../app" -m ${moduleName}/${mainClassName} ${args} %* & popd
```

There is no such directory:  "%~dp0/../app".

Perhaps this is mean to be "somewhere that we KNOW doesn't exist"..to avoid split modules or somesuch? If so, perhaps a comment in the file might help confused onlookers (like me).

**Comment by Siedlerchr** [comment]
It's a special batch variable
https://stackoverflow.com/a/112135

**Comment by transentia** [comment]
"%~dp0" is.
"%~dp0/../app" does't exist and doesn't resolve to anything...
...so adding a path that doesn't exist to the module path isn't helpful...

**Comment by Siedlerchr** [comment]
No, it does exist when the image is build with jpackage. It contains the app.cfg 
You can test the windows portable version here https://builds.jabref.org/main/  they are all built using jlink + jpackage using this plugin

**Comment by transentia** [comment]
Ahh.

So: I wasn't using jlink/jpackage (yet?)
Thus I came across this...

As I said, perhaps a comment?

Thanks.
