### ISSUE TITLE
JLink fails on certain file systems

### ISSUE THREAD

**Issue by palexdev** [beryx/badass-jlink-plugin#226]
JLink is failing for my projects with errors of type: 
`Error: java.io.UncheckedIOException: java.nio.file.FileSystemException: ... Operation not permitted`

I think this is because JLink ties to create symbolic links, which are not supported by all file systems. In fact, I'm trying to do it on an exFAT drive
Do you think this can be fixed in some way?

**Comment by CodeDead** [comment]
This is not an issue for the Gradle plugin but rather for OpenJDK:
https://wiki.openjdk.org/display/OpenJFX/Submitting+a+Bug+Report
