### ISSUE TITLE
jpackage Gradle task generates invalid Mac OSX executable when JDK version < 20

### ISSUE THREAD

**Issue by lmgithubtest** [beryx/badass-jlink-plugin#231]
I must say that I have no clue if this is caused by the badass-jlink-plugin or by a faulty JDK/JPackage, but on my machine (MacBook Air, 1. Core i5, Ventura 13.3.1 (a)) the generated binary cannot be started when the JDK used has a version lower than 20.

Example code: https://github.com/lmgithubtest/githubtest/tree/macjdkbelow20bug
On a Mac, run _./gradlew clean jpackage_ with a JDK 17 (I used Temurin 17.0.7) and try to run _build/jpackage/githubtest_: 

"githubtest” is damaged and can’t be opened. You should move it to the Bin.

JDK 19.0.2 also fails. But if I do the same with a JDK Temurin 20.0.1, the application starts as expected. 

As stated, I have no clue what causes this strange behaviour or even on how to debug this issue. Any hints are welcome.

**Comment by airsquared** [comment]
This is likely an error with jpackage itself. See if you are able to run it after clearing the quarantine attribute in the terminal with: `xattr -cr com.apple.quarantine /path/to/application.app`.

**Comment by airsquared** [comment]
Also try with JDK 17.0.8, there was an issue related to macOS signing fixed in that version.

**Comment by lmgithubtest** [comment]
Quarantine was not an issue. Using Oracle JDK 17.0.8 fixed it. So definitively not a bug in the plugin.

Since there is no Temurin 17.0.8, I guess it is back to Oracle. Thanks for your help.
