### ISSUE TITLE
Unresolved reference: mainJar

### ISSUE THREAD

**Issue by paweldzielak** [beryx/badass-jlink-plugin#233]
Accoding to [docs](https://badass-runtime-plugin.beryx.org/releases/latest/#_jpackage) we can set `mainJar` in `jpackage` task, but in intelliJ it is shown as error, and running with `gradlew jpackage` resolves to: 

**Unresolved reference: mainJar**

Tested with:
- Windows 11, Java 19 or 17. 

```kotlin
kotlin("jvm") version "1.8.21"
id("org.beryx.jlink") version "2.26.0"
```

adding to `imageOptions` resolves to:
*Cannot have both --main-jar and --module Options*

**Comment by airsquared** [comment]
The documentation you linked is for the Runtime Plugin, not the JLink Plugin. `mainJar` is not available in the JLink plugin. If you are having an issue with the Runtime Plugin, create an issue at [beryx/badass-runtime-plugin](https://github.com/beryx/badass-runtime-plugin).
