### ISSUE TITLE
jlinkZip task not executing

### ISSUE THREAD

**Issue by joeo73** [beryx/badass-jlink-plugin#24]
Ref: https://github.com/beryx/badass-runtime-plugin/issues/3

gradle clean jlinkZip
gradle clean
gradle clean jlinkZip <-- Does not produce new zip file.

'gradle -is clean jlinkZip --info --console=plain' outputs:

> Task :itemsense-v2-service:jlinkZip UP-TO-DATE
Skipping task ':itemsense-v2-service:jlinkZip' as it is up-to-date.
:itemsense-v2-service:jlinkZip (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 0.0 secs.

**Comment by joeo73** [comment]
I checked the clean task and the build directly in the sub project is removed.

**Comment by siordache** [comment]
I was able to reproduce this issue by configuring both `imageName` and `imageZip` in the `jlink` script block. If this is also the case in your build script, then release 2.6.0 should fix the problem.
Please give it a try.
