### ISSUE TITLE
Deprecated option

### ISSUE THREAD

**Issue by nlisker** [beryx/badass-jlink-plugin#272]
When using
```
options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
```
the option `'--compress', '2'` is deprecated. It should be replaced with `"--compress", "zip-6"`, where 6 is the equivalent compression level of the old `2` level. Other zip compression levels are also viable.

**Comment by xzel23** [comment]
The "zip-..." compression values were introduced after JDK 17 and would give an error when using that version. The old '2' value is supported up to at least Java 23 and works for all Java versions currently supported by the plugin. As this only refers to example code and documentation and the current value works in all cases, this should be left unchanged until we either move past Java 17 as the minimal version or a new Java version is released that drops support for the old values.
