### ISSUE TITLE
3.1.0 is released but not published

### ISSUE THREAD

**Issue by ice1000** [beryx/badass-jlink-plugin#282]
Latest version is still 3.1.0-rc-1

https://plugins.gradle.org/plugin/org.beryx.jlink

![image](https://github.com/user-attachments/assets/2cf568e5-2316-40bb-80e6-6a4b1417eae7)

**Comment by xzel23** [comment]
Ah, it should be published and work. Thank you for bringing this up. 

Seems I had a little trouble with the release script and so the documentation was not updated. But you should be able to use 3.1 anyway. I am thinking about doing a 3.1.1 release in the coming days that fixes an issue when having annotations on module declarations (i.e. when the module is @Nullmarked using specify annotations) and I will see to it doing it right that time.

**Comment by ice1000** [comment]
Thanks!

**Comment by xzel23** [comment]
fixed in 3.1.1
