### ISSUE TITLE
Compatibility Gradle 6.0

### ISSUE THREAD

**Issue by Ealrann** [beryx/badass-jlink-plugin#29]
Hello,

When running a gradle build (gradle v5.x) with badass-jlink-plugin, the following warning appears:

> Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.                                                                      Use '--warning-mode all' to show the individual deprecation warnings.

When running with `--warning-mode all`, here the warning:

> Configure project :org.sheepy.vsand                                                                                                                            Using method ObjectFactory.property() method to create a property of type Map has been deprecated. This will fail with an error in Gradle 6.0. Please use  the ObjectFactory.mapProperty() method instead.

When I remove the jlink plugin, the warning doesn't appear anymore. 

I use it in the project [VSand](https://github.com/Ealrann/VSand).

**Comment by siordache** [comment]
Thanks for reporting. Fixed in 2.6.2.

**Comment by Ealrann** [comment]
Thank you, no warning anymore !
