### ISSUE TITLE
Support multi-project builds

### ISSUE THREAD

**Issue by mwkroening** [beryx/badass-jlink-plugin#41]
When using this plugin on an application which is depending on another subproject, `$ ./gradlew clean jlink` will fail, as the plugin does not find the required subproject jar.

`$ ./gradlew clean jar jlink` will succeed.

Having this work as expected would prevent some trouble when changing things in the dependency.

**Comment by siordache** [comment]
I was not able to reproduce the problem with [this multi-project](https://github.com/beryx-gist/badass-jlink-example-javafx-multiproject).
Can you please provide a sample project that exhibits the described behavior?

**Comment by mwkroening** [comment]
Sorry! I should have thought about that this might be specific to my configuration.

I created an example repository here: [mwkroening/badass-jlink-missing-jar](https://github.com/mwkroening/badass-jlink-missing-jar)

**Comment by siordache** [comment]
Thanks, it works. I mean it fails.

**Comment by siordache** [comment]
Fixed in release 2.9.1.

**Comment by mwkroening** [comment]
Thanks a lot for the quick fix!
