### ISSUE TITLE
“jvm-args” will eventually be renamed to “java-options”

### ISSUE THREAD

**Issue by lenborje** [beryx/badass-jlink-plugin#44]
We must track this. [https://bugs.openjdk.java.net/browse/JDK-8221582](https://bugs.openjdk.java.net/browse/JDK-8221582)

**Comment by lenborje** [comment]
This has been implemented in the jpackage EA build 36, and we must update the plugin accordingly.

**Comment by lenborje** [comment]
It is of course trivial to change the invocation of `jpackage create-image` to specify `--java-options` instead of `--jvm-args`, but should the plugin itself also change its own option `jvmArgs` to `javaOptions`?

**Comment by siordache** [comment]
The jpackage invocation is fixed in 2.9.0.
I decided to stick with the name `jvmArgs`, because this property exists since release 2.0.0. Renaming it would be a breaking change and would require a major version increment.
