### ISSUE TITLE
Warning when module names end with a digit.

### ISSUE THREAD

**Issue by lenborje** [beryx/badass-jlink-plugin#45]
I have dependencies on, among others, `org.apache.commons:commons-math3:3.6.1`.

When this is merged and compiled I get the following warning:

```
> Task :Base:createDelegatingModules
/Users/lennartb/RaT/git/BMF/Base/build/jlinkbase/tmpjars/commons.math3/module-info.java:2: warning: [module] module name component math3 should avoid terminal digits
open module commons.math3 {
                   ^
1 warning
```

I guess a fix could be done in `Util.getModuleName(File f)`,  but since this method mostly relies on `ModuleFinder`to infer the module name, I don't know if it's a good idea to mess with the name? I should perhaps just keep calm and ignore the warning.

**Comment by siordache** [comment]
javac also [issues warnings](https://bugs.openjdk.java.net/browse/JDK-8216185) for such module names and the openjdk developers don't plan to remove it. So maybe the plugin should also continue to print these warnings.

**Comment by lenborje** [comment]
OK, I agree. Keep it!
