### ISSUE TITLE
prepareModulesDir task fails with "Cannot retrieve module name from module-info.java"

### ISSUE THREAD

**Issue by nemphys** [beryx/badass-jlink-plugin#46]
Hi, I am trying to build an image for my multi-module project and the prepareModulesDir task fails with the message in the issue title (after creating a 23MB merged jar).

I am afraid I cannot post the full build.gradle here since it is an internal company project, but the dependencies of the submodules are:

ui:
dependencies {
    api project(':common')
    api project(':env')
    api project(':model')
    api project(':api')
    api project(':control')
    implementation 'org.reactfx:reactfx:2.0-M5'
    implementation 'org.kordamp.ikonli:ikonli-javafx:11.2.0'
    implementation 'org.kordamp.ikonli:ikonli-fontawesome-pack:11.2.0'
    implementation 'org.kordamp.ikonli:ikonli-material-pack:11.2.0'
    implementation 'org.controlsfx:controlsfx:11.0.0-RC2'
    implementation 'com.jfoenix:jfoenix:9.0.8'
    implementation 'org.apache.commons:commons-lang3:3.8.1'
    implementation 'commons-io:commons-io:2.6'
    implementation 'org.apache.poi:poi:4.0.1'
    implementation 'org.apache.poi:poi-ooxml:4.0.1'
    implementation files('libs/scenicview.jar')
}

api:
dependencies {
    api project(':model')
    api project(':env')
    api project(':common')
    implementation 'org.reactfx:reactfx:2.0-M5'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.9.8'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.9.8'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.9.8'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.9.8'
    implementation 'org.apache.httpcomponents:httpclient:4.5.7'
    implementation 'org.apache.httpcomponents:httpcore:4.4.11'
    implementation "org.cache2k:cache2k-api:${cache2kVersion}"
    runtimeOnly "org.cache2k:cache2k-core:${cache2kVersion}"
}

control: 
dependencies {
    api project(':common')
    api project(':env')
    api project(':model')
    implementation 'org.reactfx:reactfx:2.0-M5'
    implementation 'org.kordamp.ikonli:ikonli-javafx:11.2.0'
    implementation 'org.kordamp.ikonli:ikonli-fontawesome-pack:11.2.0'
    implementation 'org.kordamp.ikonli:ikonli-material-pack:11.2.0'
    implementation 'org.controlsfx:controlsfx:11.0.0-RC2'
    implementation 'com.jfoenix:jfoenix:9.0.8'
    implementation 'org.apache.commons:commons-collections4:4.2'
    implementation 'org.apache.commons:commons-lang3:3.8.1'
}

env:
dependencies {
    api project(':common')
    api project(':model')
    api 'net.engio:mbassador:1.3.2'
}

model:
dependencies {
    implementation 'org.reactfx:reactfx:2.0-M5'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.9.8'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.9.8'
}

I don't know if you will be able to debug this, but it might be helpful to make the "Cannot retrieve module name from module-info.java" a little more verbose (eg. print out the source string it is trying to match against the patterns), so that one can have an idea of where the problem is in big projects.

**Comment by siordache** [comment]
I made the error message more verbose in release 2.9.4. It now includes the path to the module-info.java file and its content.

**Comment by nemphys** [comment]
You really are fast!
Thank you, will report back soon.

**Comment by nemphys** [comment]
OK, found the culprit:
my gui module's module-info.java file begins with 2 import statements (local spi providers) before the module name declaration, which seems to confuse the module name the matching logic.
I suppose the pattern has to be adjusted, so that it filters out import statements.

**Comment by nemphys** [comment]
Also (this is quite irrelevant to this issue), is there a way to use a different setting for addExtraModulePath per targetPlatform? I am trying to build for win/osx/linux with javafx and have to include the javafx jmods of each platform to the jlink module path, but cannot figure a way to do it.

**Comment by siordache** [comment]
In the next days, I will publish a new release with better support for javafx jmods. I will also adjust the pattern used for retrieving the module name from module-info.java.

**Comment by nemphys** [comment]
Great, sounds perfect!

**Comment by siordache** [comment]
@nemphys  The plugin now supports [addExtraModulePath per targetPlatform](https://github.com/beryx/badass-jlink-plugin/releases/tag/v2.10.0).

**Comment by siordache** [comment]
@nemphys Release 2.10.1 allows import statements in module-info.java.

**Comment by nemphys** [comment]
Thank you very much, you are very fast. I also saw that there is now much better support for multi-platform builds with JavaFX, greatly appreciated.
