### ISSUE TITLE
jpackage imageName and installerName not defaulting to launcher name

### ISSUE THREAD

**Issue by msgilligan** [beryx/badass-jlink-plugin#48]
I'm using version 2.9.4 and had to manually set `imageName` and `installerName` in the `jpackage` block since they weren't defaulting to `name` from the `launcher` block as documented.

I'm using OpenJDK 12 on macOS 10.13.6.

**Comment by siordache** [comment]
@msgilligan Fixed in release 2.10.1

**Comment by msgilligan** [comment]
Upgraded and it's working properly now -- thanks!
