### ISSUE TITLE
Add support for JLINK_VM_OPTIONS

### ISSUE THREAD

**Issue by Burtan** [beryx/badass-jlink-plugin#5]
The starting script contains a variable JLINK_VM_OPTIONS. I think it would be nice to have the option to add jvmArgs into the jlink {} part.

**Comment by siordache** [comment]
I will look into it.
In the meantime, you can adjust the starting scripts in a `doLast` block added to the `jlink` task, as shown in [this example](https://github.com/beryx-gist/badass-jlink-example/blob/df0638ab6a32ff47b987fd8facb5ec3ec740722e/build.gradle#L39-L55).

**Comment by siordache** [comment]
@Burtan functionality added in [release 2.0](https://badass-jlink-plugin.beryx.org/releases/2.0.1/#_launcher).

**Comment by Burtan** [comment]
Thanks for the fast update, good work!
