### ISSUE TITLE
Duplicate data in packages produced by jpackage

### ISSUE THREAD

**Issue by nemphys** [beryx/badass-jlink-plugin#51]
I tried making a macOs .app using the jpackage functionality for the first time and, although all went well and the app works as expected, the total size of the app directory is 1.5x the size it should be (the jlink task produces a total size of ~100MB in my case, whereas the .app is ~150MB).
After checking the contents of the .app I noticed something weird:
apart from the Plugins/Java.runtime directory (which seems to include all of the jlink task results), there is a Java/mods directory, which includes separate jar files + the merged module file. If I understand correctly, all these jars are already merged inside the "modules" file residing in the libs directory (Plugins/Java.runtime/contents/home/lib) of the runtime image produced by jlink.
Although I prefer to have separate jars than the huge uber-merged modules file produced by jlink (this is another discussion, I would love to have some more info on this and whether it is optional), there seems to be some kind of duplication here.
Any thoughts would be appreciated.

EDIT: I just deleted the Java/mods directory from the produced .app and the app still launches and works fine. This verifies that the directory is unneeded and I am wondering why it is being produced. I suspect it is a jpackage thing and the badass plugin has nothing to do with it.

**Comment by siordache** [comment]
Yes, it looks like a jpackage thing.

**Comment by msgilligan** [comment]
Should we report this issue to `jpackage`?

**Comment by DJViking** [comment]
If this is still an issue we should report it to jpackage on core-libs-dev@openjdk.java.net
Have you tried with the latest JDK-14 jpackage build if this is still a problem? https://jdk.java.net/jpackage

I cannot see that this is a reported bug with jpackage:
https://bugs.openjdk.java.net/issues/?jql=project in (JDK) AND component in (tools) AND Subcomponent in (jpackage)

**Comment by tobiasdiez** [comment]
The two issues https://bugs.openjdk.java.net/browse/JDK-8236830 and https://bugs.openjdk.java.net/browse/JDK-8249011 were closed with the argument that this folder is only included if jpackage is invoked with the wrong arguments, i.e. jpackage includes everything that is in the folder passed as `--input`. So I guess the problem does lie in this gradle plugin and how it invokes jpackage.

**Comment by siordache** [comment]
Please check and report if duplicate data is still produced when using org.beryx.jlink 2.21.1.

**Comment by tobiasdiez** [comment]
Thanks a lot! It worked for us and reduced the installer size by almost 50%.

**Comment by nemphys** [comment]
Indeed, it seems that the issue is now resolved.
Thank you.

**Comment by siordache** [comment]
Great! Thank you both for the feedback.

**Comment by msgilligan** [comment]
Thanks for this. It's saves about 9-10 Mb (after compression) in a trivial app:
Before:

![BA_JLink_2_21_0](https://user-images.githubusercontent.com/61612/88602011-ac85b580-d026-11ea-9fdb-b1fb00c53062.png)
After:

![BA_JLink_2_21_1](https://user-images.githubusercontent.com/61612/88602033-b7404a80-d026-11ea-96bb-415e48f13e29.png)
