### ISSUE TITLE
Can't jlink modular FX project

### ISSUE THREAD

**Issue by zolt** [beryx/badass-jlink-plugin#55]
Hi.
I'm trying to jlink my project with your plugin, but get some errors
`Task :createMergedModule FAILED`
`ccm-thermometerls/build/jlinkbase/tmpjars/ru.ccm.calibration.merged.module/module-info.java:12: error: module not found: javafx.graphics
    requires javafx.graphics;`
`ccm-thermometerls/build/jlinkbase/tmpjars/ru.ccm.calibration.merged.module/module-info.java:13: error: module not found: javafx.controls
    requires javafx.controls;`
`ccm-thermometerls/build/jlinkbase/tmpjars/ru.ccm.calibration.merged.module/module-info.java:15: error: module not found: javafx.base
    requires javafx.base;`

As I understand, when we trying to compile `module-info.java`, we have no javafx libs in classpath. What am I doing wrong? Can you help me? My project in attached file.
Use gradle 5.2.1
[ccm-thermometerls.zip](https://github.com/beryx/badass-jlink-plugin/files/3176024/ccm-thermometerls.zip)

**Comment by hohonuuli** [comment]
@zolt I'm running into this exact same issue. Did you figure out a solution?
