### ISSUE TITLE
Implementation not available on jlink task

### ISSUE THREAD

**Issue by Burtan** [beryx/badass-jlink-plugin#58]
Hi,
I'm using [google-oauth-java-client](https://github.com/googleapis/google-oauth-java-client) for login purposes and everything works fine when I run the application via gradle run. However, when using jlink I get the following error:
```
Defaulting Uptime to NOIMPL due to (java.lang.UnsupportedOperationException) Implementation not available in this environment
```

It seems that some dependencies are not part of the custom runtime generated by jlink.

Any ideas?

**Comment by siordache** [comment]
Try this:

    jlink {
        ...
        mergedModule {
            additive = true
            requires 'java.management'
            ...
        }
    }
