### ISSUE TITLE
[Question] No .bat console

### ISSUE THREAD

**Issue by Ealrann** [beryx/badass-jlink-plugin#60]
Hello,

My question is not directly related to the badass plugin, but maybe you already found some good workaround for this problem.

The windows console (when you launch the .bat) is tedious for the user in my context, and I'd like to {don't launch it | hide it | disable the quick edit mode}. I found some solutions, but nothing really clean.

Maybe you have any advice about that?

**Comment by siordache** [comment]
Did you try the  [jpackage](https://badass-jlink-plugin.beryx.org/releases/latest/#_jpackage) task yet?

**Comment by Ealrann** [comment]
Ok, looks like a perfect solution indeed. I thought it was only for creating installers, but nope. Thank you :)
