### ISSUE TITLE
error: cannot find symbol caused by provides

### ISSUE THREAD

**Issue by rashaverak** [beryx/badass-jlink-plugin#62]
error:
> > Task :createMergedModule
> Cannot derive uses clause from service loader invocation in: com/fasterxml/jackson/databind/ObjectMapper.secureGetServiceLoader().
> Cannot derive uses clause from service loader invocation in: com/fasterxml/jackson/databind/ObjectMapper$2.run().
> Cannot derive uses clause from service loader invocation in: org/apache/commons/compress/utils/ServiceLoaderIterator.<init>().
> .../build/jlinkbase/tmpjars/....merged.module/module-info.java:453: error: cannot find symbol
>     provides org.openqa.selenium.WebDriverInfo with org.openqa.selenium.chrome.ChromeDriverInfo;
>                                 ^
>   symbol:   class WebDriverInfo
>   location: package org.openqa.selenium
> 1 error
> 
> > Task :createMergedModule FAILED
> 

I am still lost with the module-java but when I try just out of curiosity to copy the line causing issue to my own module-java

> requires selenium.chrome.driver;
>     requires selenium.api;
>     provides org.openqa.selenium.WebDriverInfo with org.openqa.selenium.chrome.ChromeDriverInfo;

intelliJ tell me that "The service implementation must be defined in the same module as the provides directive" as pop up over the ChromeDriverInfo, not sure if it is the same case for the module-info you generate for the libs merged module.

The java code which the provide is based upon look like this

> @AutoService(WebDriverInfo.class)
> public class ChromeDriverInfo implements WebDriverInfo {

**Comment by siordache** [comment]
Do you get the same error message if you add the following line to your build.gradle?

    forceMerge "selenium"

**Comment by rashaverak** [comment]
Helped to get rid of the error. Thank you.
