### ISSUE TITLE
jpackage Error reading module: /usr/lib/jvm/openjdk-13-linux64/jdk-13/jmods/jdk.security.jgss.jmod

### ISSUE THREAD

**Issue by rashaverak** [beryx/badass-jlink-plugin#63]
error

```
> Task :jlink FAILED
Error: Error reading module: /usr/lib/jvm/openjdk-13-linux64/jdk-13/jmods/jdk.security.jgss.jmod


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jlink'.
> Process 'command '/usr/lib/jvm/openjdk-12/bin/jlink'' finished with non-zero exit value 1
```

build.gradle

```
targetPlatform("linux") {
        jdkHome = "/usr/lib/jvm/openjdk-13-linux64/jdk-13"
//        addExtraModulePath("/usr/lib/openjfx/linux-s390x/jmods")
    }

    jpackage {
        jpackageHome = '/usr/lib/jvm/openjdk-13-linux64/jdk-13'
        outputDir = 'SD-linux'
        // imageOutputDir = file("$buildDir/my-packaging-image")
        // installerOutputDir = file("$buildDir/my-packaging-installer")
        imageName = 'SD'
//        imageOptions = ['--win-console']
        skipInstaller = false
        installerName = 'SD'
        installerType = 'rpm' //exe, msi, dmg, rpm
//        installerOptions = ['--win-console', '--win-menu', '--win-shortcut']
//        targetPlatform = "linux"
    }
```

/usr/lib/jvm/openjdk-13-linux64/jdk-13/jmods/jdk.security.jgss.jmod exists and everyone has read rights

it is the latest build of jdk-13 23
https://jdk.java.net/13/

**Comment by siordache** [comment]
It doesn't work because you use a JDK-12 jlink (/usr/lib/jvm/openjdk-12/bin/jlink) to create a JDK-13 custom runtime image. You have two options:

1. Use a JDK-13 jlink by setting:
```
    jlink {
        javaHome = '/usr/lib/jvm/openjdk-13-linux64/jdk-13'
        ...
    }
```

2. Create a JDK-12 custom runtime image by setting: 

```
    targetPlatform("linux") {
        jdkHome = "/usr/lib/jvm/openjdk-12"
    }
```

**Comment by rashaverak** [comment]
It helped indeed but somehow the result does not seems to be right even if it wrote build successfull. I do not want to use you as my personal assistant, but isnt there supposed to be launcher created ? What I got is in my build/ folder new folder "image" which look like a java runtime but there is no launcher and there is not my own jar, I do not even see anything I would say could be merged libs jar. Do I maybe look into wrong directory ? There is file called the same as my launcher should be which tries to run the proper module

```
#!/bin/sh
DIR="${0%/*}"
"$DIR/java"  -m myModule  "$@"
```

but there is no java folder anywhere in the whole build/image/ directory structure

the only compiled classes I see are under /build/classes/java

the merged jar seems to be in /build/jlinkbase/tmpmerged

Maybe just my expectations are wrong and am I supposed to finish the bundle manually ? To put the merged libs jar, compiled classes, resources, runtime together with some extra gradle task I write on my own ?

**Comment by siordache** [comment]
The build/image directory should contain everything you need. You will not find your own jar (or other jars required by your application) there, because jlink merges everything into a single big file: `build/image/lib/modules`.

The `build/image/bin` contains launchers for your application (a bash script and a .bat file). The [name of the launch script file](https://badass-jlink-plugin.beryx.org/releases/latest/#_launcher) corresponds by default to your project name.

**Comment by rashaverak** [comment]
Thank you, sorry for wasting your time.

**Comment by rashaverak** [comment]
Is it possible to call jpackage multiple times ? In case I want to build for linux and windows ?

```
jpackage {
        jpackageHome = '/usr/lib/jvm/openjdk-13-linux64/jdk-13'
        outputDir = 'SD-linux'
        imageName = 'SDLinux'
        skipInstaller = false
        installerName = 'SD'
    }

    jpackage {
        jpackageHome = '/usr/lib/jvm/openjdk-13-win/jdk-13'
        outputDir = 'SD-windows'
        imageName = 'SDWin'
        skipInstaller = false
        installerName = 'SuitestDrive'
        installerType = 'exe'
    }
```

It seems the outputDir is ignored completely, because it always only create "image" folder. Also there is no exe file created. In case I am missing compiler to create such file, maybe it could warn ?

**Comment by siordache** [comment]
No.  [JEP 343](https://openjdk.java.net/jeps/343) says:

> There will be no support for cross compilation. For example, in order to create Windows packages one must run the tool on Windows. The tool can depend upon platform-specific tools.

After executing `./gradlew jpackage` you should use the installer specific to your platform in the `build/jpackage` directory.
