### ISSUE TITLE
Do you support multiple launchers ?

### ISSUE THREAD

**Issue by rashaverak** [beryx/badass-jlink-plugin#65]
I have 2 different main classes in my project and would like to create 2 different launchers for them.

**Comment by siordache** [comment]
The next release will support multiple launchers. It will probably be available tomorrow.

**Comment by siordache** [comment]
Support for multiple launchers is available in release 2.11.0.
See usage examples [here](https://github.com/beryx/badass-jlink-plugin/blob/9e41fe4b4aa59132de3423709afbd694fc4cae1d/src/test/resources/multi-launch/build.gradle#L17-L20) and in the [documentation](https://badass-jlink-plugin.beryx.org/releases/latest/#_secondarylauncher).

**Comment by rashaverak** [comment]
Do you also plan to support these secondary launchers with the jpackage ?

**Comment by siordache** [comment]
Yes, in the next release.

**Comment by siordache** [comment]
Version 2.1..11 released. Now, the jpackage task also supports multiple launchers.

**Comment by rashaverak** [comment]
Great, work fine. Maybe with one limitation.

The mainClass in gradle is defined like this 
mainClassName = "$moduleName/$mainClass1"

If I would define the secondary launcher className in the same way
mainClass = "$moduleName/$mainClass2"

The result in the cfg is actually $moduleName/$moduleName/$mainClass2

so for the secondary launcher it must be 
mainClass = "$mainClass2"

Which is fine for me as I have both main classes in the same module but might be a limitation in some cases.

**Comment by siordache** [comment]
@rashaverak  If necessary, you can configure a [different moduleName](https://github.com/beryx/badass-jlink-plugin/blob/9e41fe4b4aa59132de3423709afbd694fc4cae1d/src/test/resources/multi-launch/build.gradle#L23-L24) in the `secondaryLauncher` block:

    secondaryLauncher {
        name = 'secondaryHello'
        moduleName = 'org.example.secondary'
        mainClass = 'org.example.secondary.SecondaryHello'
    }
