### ISSUE TITLE
Error Module already present

### ISSUE THREAD

**Issue by OssNass** [beryx/badass-jlink-plugin#68]
I have the following Gradle build file:
```
plugins {
    id 'java'
    id 'org.openjfx.javafxplugin' version '0.0.7'
    id 'org.beryx.jlink' version '2.11.1'
    id 'application'
}


group 'org.sarc'
version '1.0-SNAPSHOT'

sourceCompatibility = 11

javafx {
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    // https://mvnrepository.com/artifact/org.apache.poi/poi-ooxml
    compile group: 'org.apache.poi', name: 'poi-ooxml', version: '4.1.0'
    compile group: 'org.ocomp', name: 'simplefx-11', version: '0.1'
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

ext {
    moduleName = 'org.sarc.bazinga'
    moduleLaunchPoint = 'org.sarc.bazinga.app.Main'
}

sourceSets {
    main.output.resourcesDir = main.java.outputDir
}

jlink() {
    def javaHome = System.properties.'java.home'
    options = ['--strip-debug', '--compress', '2',
               '--no-header-files', '--no-man-pages',
               '--output', "${moduleName}"
    ]
    launcher {
        name = 'bazinga'
    }
    
    mergedModule {
        requires 'java.desktop'
        requires 'java.logging'
        requires 'java.security.jgss'
        requires 'jdk.javadoc'
        requires 'java.xml'
        requires 'java.xml.crypto'

    }
}
mainClassName="${moduleName}/${moduleLaunchPoint}"
```

And I have the following module-info.java file:

```
module org.sarc.bazinga {

    exports org.sarc.bazinga.app;

    requires javafx.base;
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.graphics;
    requires poi;
    requires poi.ooxml;
    requires org.ocomp.simplefx;

    opens org.sarc.bazinga.gui to javafx.fxml;

}
```

However when I try to run `gradle jlink` I get the following error:
Found module name 'org.sarc.bazinga'
```

> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :prepareMergedJarsDir UP-TO-DATE
> Task :createMergedModule UP-TO-DATE
> Task :createDelegatingModules UP-TO-DATE
> Task :prepareModulesDir UP-TO-DATE

> Task :jlink FAILED
java.base file:///usr/lib/jvm/java-11-openjdk/jmods/java.base.jmod
java.compiler file:///usr/lib/jvm/java-11-openjdk/jmods/java.compiler.jmod
java.datatransfer file:///usr/lib/jvm/java-11-openjdk/jmods/java.datatransfer.jmod
java.desktop file:///usr/lib/jvm/java-11-openjdk/jmods/java.desktop.jmod
java.logging file:///usr/lib/jvm/java-11-openjdk/jmods/java.logging.jmod
java.naming file:///usr/lib/jvm/java-11-openjdk/jmods/java.naming.jmod
java.prefs file:///usr/lib/jvm/java-11-openjdk/jmods/java.prefs.jmod
java.scripting file:///usr/lib/jvm/java-11-openjdk/jmods/java.scripting.jmod
java.security.jgss file:///usr/lib/jvm/java-11-openjdk/jmods/java.security.jgss.jmod
java.security.sasl file:///usr/lib/jvm/java-11-openjdk/jmods/java.security.sasl.jmod
java.xml file:///usr/lib/jvm/java-11-openjdk/jmods/java.xml.jmod
java.xml.crypto file:///usr/lib/jvm/java-11-openjdk/jmods/java.xml.crypto.jmod
javafx.base file:///home/ossama/IdeaProjects/bazinga/build/jlinkbase/jlinkjars/javafx-base-11.0.2-linux.jar
javafx.controls file:///home/ossama/IdeaProjects/bazinga/build/jlinkbase/jlinkjars/javafx-controls-11.0.2-linux.jar
javafx.fxml file:///home/ossama/IdeaProjects/bazinga/build/jlinkbase/jlinkjars/javafx-fxml-11.0.2-linux.jar
javafx.graphics file:///home/ossama/IdeaProjects/bazinga/build/jlinkbase/jlinkjars/javafx-graphics-11.0.2-linux.jar
jdk.compiler file:///usr/lib/jvm/java-11-openjdk/jmods/jdk.compiler.jmod
jdk.javadoc file:///usr/lib/jvm/java-11-openjdk/jmods/jdk.javadoc.jmod
jdk.unsupported file:///usr/lib/jvm/java-11-openjdk/jmods/jdk.unsupported.jmod
org.ocomp.simplefx file:///home/ossama/IdeaProjects/bazinga/build/jlinkbase/jlinkjars/simplefx-11-0.1.jar
org.sarc.bazinga file:///home/ossama/IdeaProjects/bazinga/build/jlinkbase/jlinkjars/bazinga-1.0-SNAPSHOT.jar
org.sarc.merged.module file:///home/ossama/IdeaProjects/bazinga/build/jlinkbase/jlinkjars/bazinga.merged.module.jar
poi file:///home/ossama/IdeaProjects/bazinga/build/jlinkbase/jlinkjars/poi-4.1.0.jar
poi.ooxml file:///home/ossama/IdeaProjects/bazinga/build/jlinkbase/jlinkjars/poi-ooxml-4.1.0.jar

Providers:
  jdk.compiler provides com.sun.tools.javac.platform.PlatformProvider used by jdk.compiler
  java.desktop provides java.net.ContentHandlerFactory used by java.base
  java.base provides java.nio.file.spi.FileSystemProvider used by java.base
  java.naming provides java.security.Provider used by java.base
  java.security.jgss provides java.security.Provider used by java.base
  java.security.sasl provides java.security.Provider used by java.base
  java.xml.crypto provides java.security.Provider used by java.base
  jdk.compiler provides java.util.spi.ToolProvider used by java.base
  jdk.javadoc provides java.util.spi.ToolProvider used by java.base
  java.desktop provides javax.print.PrintServiceLookup used by java.desktop
  java.desktop provides javax.print.StreamPrintServiceFactory used by java.desktop
  java.desktop provides javax.sound.midi.spi.MidiDeviceProvider used by java.desktop
  java.desktop provides javax.sound.midi.spi.MidiFileReader used by java.desktop
  java.desktop provides javax.sound.midi.spi.MidiFileWriter used by java.desktop
  java.desktop provides javax.sound.midi.spi.SoundbankReader used by java.desktop
  java.desktop provides javax.sound.sampled.spi.AudioFileReader used by java.desktop
  java.desktop provides javax.sound.sampled.spi.AudioFileWriter used by java.desktop
  java.desktop provides javax.sound.sampled.spi.FormatConversionProvider used by java.desktop
  java.desktop provides javax.sound.sampled.spi.MixerProvider used by java.desktop
  jdk.javadoc provides javax.tools.DocumentationTool used by java.compiler
  jdk.compiler provides javax.tools.JavaCompiler used by java.compiler
  jdk.compiler provides javax.tools.Tool not used by any observable module
  jdk.javadoc provides javax.tools.Tool not used by any observable module
  java.logging provides jdk.internal.logger.DefaultLoggerFinder used by java.base
  java.desktop provides sun.datatransfer.DesktopDatatransferService used by java.datatransfer
Error: Resource /org.sarc.bazinga/module-info.class already present
```

Running the application from the IDE is fine, jlinking is the problem

**Comment by siordache** [comment]
Do you get the same error if you run `gradle clean jlink`?

If yes, please execute:
```
jar tvf build/jlinkbase/jlinkjars/<your-bazinga-jar>
```
and post the output here.

**Comment by OssNass** [comment]
I executed `gradle clean jlink` to no use, so per your suggestion I executed the command  `jar` on the normal jar (not merged module) to the following result:
`jar tvf build/jlinkbase/jlinkjars/bazinga-1.0-SNAPSHOT.jar 
     0 Fri Jun 28 21:32:04 EEST 2019 META-INF/
    25 Fri Jun 28 21:32:04 EEST 2019 META-INF/MANIFEST.MF
   396 Fri Jun 28 21:32:04 EEST 2019 module-info.class
     0 Fri Jun 28 21:32:04 EEST 2019 org/
     0 Fri Jun 28 21:32:04 EEST 2019 org/sarc/
     0 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/
     0 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/app/
  1541 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/app/Main.class
     0 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/gui/
   213 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/gui/LangKeys2.class
  8053 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/gui/FrmMain.class
   397 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/gui/ExtraWork.class
  7307 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/gui/LstRegionCell.class
   834 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/gui/FrmMain$1.class
     0 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/data/
  1955 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/data/Family.class
  1708 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/data/RegionStatus.class
  3755 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/data/Region.class
  5472 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/data/RegionProcessor.class
  1358 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/data/RegionType.class
  3446 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/data/Person.class
  1463 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/data/ProcessingStatus.class
  2138 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/data/Duration.class
  1146 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/data/Constants.class
   957 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/data/Sex.class
   396 Fri Jun 28 21:32:04 EEST 2019 module-info.class
  1541 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/app/Main.class
   213 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/gui/LangKeys2.class
  8053 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/gui/FrmMain.class
   397 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/gui/ExtraWork.class
  7307 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/gui/LstRegionCell.class
   834 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/gui/FrmMain$1.class
  1955 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/data/Family.class
  1708 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/data/RegionStatus.class
  3755 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/data/Region.class
  5472 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/data/RegionProcessor.class
  1358 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/data/RegionType.class
  3446 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/data/Person.class
  1463 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/data/ProcessingStatus.class
  2138 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/data/Duration.class
  1146 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/data/Constants.class
   957 Fri Jun 28 21:32:04 EEST 2019 org/sarc/bazinga/data/Sex.class
`
As you noticed the `module-info.class` is presented twice, even though it's available once in the file as per this image from KDE's Ark
![Screenshot_٢٠١٩٠٦٢٨_٢١٣٤٠٢](https://user-images.githubusercontent.com/5196218/60363689-dbc58f80-99ec-11e9-90ef-182c0b639e76.png)

However executing the jar command on Merged module yields the following (to big to show so I uploaded a compressed version):
[x.zip](https://github.com/beryx/badass-jlink-plugin/files/3340402/x.zip)

**Comment by siordache** [comment]
Remove the following block from your build.gradle:
```
sourceSets {
    main.output.resourcesDir = main.java.outputDir
}
```

Otherwise, the jar task adds the content of `main.java.outputDir` (which means `build/classes/java/main`) twice: once as location of the compiled files and once as location of the resources. That's why all .class files are duplicated in the resulting jar.

**Comment by OssNass** [comment]
In addition to removing
```
sourceSets {
    main.output.resourcesDir = main.java.outputDir
}
```
I had to remove `'--output', "${moduleName}"` from jlink options and it worked, thanks
