### ISSUE TITLE
Missing jpackage options?

### ISSUE THREAD

**Issue by danielpeintner** [beryx/badass-jlink-plugin#69]
First of all thanks for the plugin!

I used [javafx-maven-plugin](https://github.com/javafx-maven-plugin/javafx-maven-plugin) to create installers for Java8 in the past.
Moving from Java8 to Java11 I found your plugin very useful. It works fine but it seems to miss some parts (or maybe the experimental jpackage work?) OR I am not able to set it properly.

# Application Icon

In the *old* javapackager case it was sufficient to place an `app.ico` file in `src/main/deploy/package/windows` folder for Windows and the icon was picked up.
Similarly for other platforms. This does not work anymore.

Alternatively one could use icon="..." to set another location

setting icon='app.ico' in launcher sections fails with 
`> Could not set unknown property 'icon' for org.beryx.jlink.data.LauncherData`

setting icon='app.ico' in jpackage sections fails with 
`> Could not set unknown property 'icon' for org.beryx.jlink.data.JPackageData`

# File Associations

It used to be possible to associate certain extensions to the app and according to https://openjdk.java.net/jeps/343 it should be still possible.

Given the work is still on-going I assume this is not implemented yet. Correct?
Or I cannot figure out the proper syntax.

# Version

Setting version = '2019.01' in launcher sections works but does not seem to have any effect. The jpackage task still creates app-1.0.exe (or app-1.0.msi) and not app-2019.01.exe as I would have assumed.

I looked at the examples you referenced but I did not find examples for the afore mentioned options.
Is there some documentation or anything else one can look at to know how given jpackage options are mapped in this plugin?

Thanks for your great work and efforts again!

**Comment by siordache** [comment]
@danielpeintner 
The plugin maps only a few jpackage options. The remaining ones can be passed via `imageOptions` and `installerOptions`.
See the updated [badass-jlink-example-richtextfx](https://github.com/beryx-gist/badass-jlink-example-richtextfx/blob/ba259bdbce7e6ea85db46aebc386e584e1a5ec35/build.gradle#L30-L34) project for examples.

**Comment by danielpeintner** [comment]
Thanks! It worked and I got the idea behind...
