### ISSUE TITLE
Error when a dependency has no classes in a package

### ISSUE THREAD

**Issue by zakgof** [beryx/badass-jlink-plugin#7]
Try to build a project with this dependency:

`compile 'org.apache.poi:poi-ooxml:4.0.0'`

Build fails with the error 

````> Task :createMergedModule
Cannot derive uses clause from service loader invocation in: org/apache/commons/compress/utils/ServiceLoaderIterator.<init>().
H:\Pr\psr\build\jlinkbase\tmpjars\psr.merged.module\module-info.java:253: error: package is empty or does not exist: org.apache.poi.poifs
    exports org.apache.poi.poifs;
                          ^
1 error
````
My guess is that it happens because the package `org.apache.poi.poifs` does not have any clasess (but 
`org.apache.poi.poifs.crypt` does). The plugin is still trying to export `org.apache.poi.poifs` in a generated module definition.

**Comment by siordache** [comment]
Can you post your build.gradle or a link to your project?

**Comment by siordache** [comment]
@zakgof Do you still have this problem?

**Comment by zakgof** [comment]
Unfortunately, I was not able to reproduce the issue with a small clean project, let's just close it.
