### ISSUE TITLE
DMG Installer skipped -- app identifier must be specified

### ISSUE THREAD

**Issue by msgilligan** [beryx/badass-jlink-plugin#74]
On macOS I'm trying to build a DMG image and getting the following error:

```
Bundler DMG Installer skipped because of a configuration problem: When using an external app image you must specify the identifier.. 
Advice to fix: Set the identifier via the -appId CLI flag, the fx:application/@id ANT attribute, or via the 'identifier' bundler argument.
```

I have Build 8 (2019/6/21) of `jpackage` installed in `BADASS_JLINK_JPACKAGE_HOME`.

My `jlink` block:

```
jlink {
    addExtraDependencies("javafx")
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    launcher {
        name = 'WalletTemplate'
        jvmArgs = []
    }
    jpackage {
        jpackageHome = System.getenv('BADASS_JLINK_JPACKAGE_HOME')
        skipInstaller = false
        installerType = "dmg"
    }
}
```

Note: Copying the actual generated `jpackage` command and adding ` --identifier WalletTemplate` seems to produce a valid DMG.

**Comment by siordache** [comment]
I will look into it. In the meantime, try this:

```
jpackage {
    jpackageHome = System.getenv('BADASS_JLINK_JPACKAGE_HOME')
    skipInstaller = false
    installerType = "dmg"
    installerOptions = ["--identifier", "WalletTemplate"]
}
```

**Comment by msgilligan** [comment]
Good suggestion, I will try that.

**Comment by msgilligan** [comment]
Yes, that seems to work. So we could just document as a mandatory option, or automatically set it by default.

**Comment by siordache** [comment]
In 2.14.1, the plugin sets the --identifier option by itself. 
Default value: the main class. 
Ìn the `jpackage` block you can now customize this value using the newly introduced property `identifier`.

**Comment by msgilligan** [comment]
This [seems to work](https://github.com/ConsensusJ/bitcoinj/commit/61f511a887c8058ecc0ad672516d8d80e851da22). Thanks!

**Comment by gleidsonmt** [comment]
Oh god, thanks..
