### ISSUE TITLE
When used in a multi-project build, forces all other project's 'jar' tasks to be built regardless of if it depends on them or not

### ISSUE THREAD

**Issue by mkobit** [beryx/badass-jlink-plugin#76]
Caused by https://github.com/beryx/badass-jlink-plugin/blob/ca5e3fad939d84bcb73e063d6af6111740c67f01/src/main/groovy/org/beryx/jlink/PrepareMergedJarsDirTask.groovy#L56

Would it be possible to use only dependencies on other projects? Possibly use variant-aware dependency management to select the `jar` variant from other projects instead?

**Comment by siordache** [comment]
In release 2.15.0, `dependsOn` is called only for the `jar` tasks of the projects on which this project depends:
https://github.com/beryx/badass-jlink-plugin/blob/45c160fa5b6a0ca3d5bf45c3dad13b4bebd720b6/src/main/groovy/org/beryx/jlink/PrepareMergedJarsDirTask.groovy#L65-L69

I know this is not an ideal solution. It would be great if you can submit a pull request that uses variant-aware dependency management.
