### ISSUE TITLE
Intermittent failures building DMG on macOS

### ISSUE THREAD

**Issue by msgilligan** [beryx/badass-jlink-plugin#77]
(This could be a bug in the `jpackage` tool.)

```
> Task :airgapfx-wallet:jpackage
java.io.IOException: Exec failed with code 1 command [[osascript, /var/folders/6d/12xt4b4m8xjf3t0059_w18bh0000gn/T/jdk.jpackage14815307871783159744/config/NetWallet-dmg-setup.scpt] in unspecified directory
```

**Comment by siordache** [comment]
Sorry for not replying sooner. I don't own a Mac, so I'm afraid I cannot help with this. Does the problem still occur with the jpackage build [14-jpackage+1-35](https://jdk.java.net/jpackage/) from 2019/8/29?

**Comment by msgilligan** [comment]
macOS is my primary development platform, so I'll be giving macOS builds and deploys a pretty solid workout over the next few months. I may also see if any of the free/open CI solutions support macOS builds.

>  Does the problem still occur with the jpackage build [14-jpackage+1-35](https://jdk.java.net/jpackage/) from 2019/8/29?

Yes, intermittently. I'm almost certain it has nothing to do with this plugin, but is an issue with the `jpackage` tool or with system utilities that it uses.

I'm considering getting involved upstream on the `jpackage` tool itself, but it's a little  unclear where to connect with people on that project and I'm not sure I really have the time. But having this tool work is really important to some of my plans and I'd like to do what I can to help out.

**Comment by DJViking** [comment]
> I'm considering getting involved upstream on the `jpackage` tool itself, but it's a little unclear where to connect with people on that project and I'm not sure I really have the time. But having this tool work is really important to some of my plans and I'd like to do what I can to help out.

You can give feedback to jpackage through the core mailinglist core-libs-dev@openjdk.java.net

Where I work we plan on building our application on Mac eventually, but currently only build on Linux and Windows so I cannot check this out myself yet.

**Comment by msgilligan** [comment]
I am no longer seeing this issue with newer `jpackage` versions. Closing.

**Comment by siordache** [comment]
@msgilligan Thanks for the update!
