### ISSUE TITLE
Using a custom gradle dependency configuration

### ISSUE THREAD

**Issue by bjorndarri** [beryx/badass-jlink-plugin#78]
I have a gradle configuration in a project of mine:

`configurations {
    serverRuntime {
        extendsFrom compile
    }
}`

I can then use this configuration, for example:

`task runServer(type: ModularJavaExec) {
    classpath = configurations.serverRuntime
}`

and

`startScripts {
    classpath = configurations.serverRuntime
}`

but I have not found a way to use this specific configuration in jlink, which seems to use the default runtime configuration.

Is there a way to specify a configuration for jlink?

**Comment by bjorndarri** [comment]
I've been looking at the code and found a reference to 

`project.configurations['runtimeClasspath']`

in the DependencyManager constructor. I played around with adding a Configuration parameter to the constructor but got quickly bogged down by all the places I had to change, I got as far as adding a Configuration variable to JLinkTaskData and a Property\<Configuration> to JLinkPluginExtension (with default value as project.configurations['runtimeClasspath']) but stopped there since I don't have any experience in groovy or gradle plugin development.

At least this looks possible, by adding a org.gradle.api.artifacts.Configuration parameter to the task.

**Comment by siordache** [comment]
The next release will support custom configurations.

**Comment by siordache** [comment]
Implemented in release 2.15.0. 
Usage:
```
jlink {
    configuration = 'serverRuntime'
    ...
}
```

**Comment by bjorndarri** [comment]
Fantastic, thank you!
