### ISSUE TITLE
Compatibility with jpackage+1-35 (29/8)

### ISSUE THREAD

**Issue by nemphys** [beryx/badass-jlink-plugin#82]
Hello,
you might want to take a look at the latest jpackage build, because I think something is broken.

It runs fine and produces a package (in macOS at least), but it seems as though the unix script template is ignored, since I have added some customisations there (-Duser.dir) that don't seem to be working.

**Comment by siordache** [comment]
Did it work with the previous jpackage build (jpackage+1-33)?
How do you pass the -Duser.dir argument?

**Comment by nemphys** [comment]
Yes, it did (does).
As for the -Duser.dir argument, I have just added it in my unix script template.

**Comment by siordache** [comment]
jpackage doesn't use the unix script. You should add `-Duser.dir` to `jvmArgs`:
```
jlink {
    launcher {
        jvmArgs = ['-Duser.dir=my/user/dir']
        ...
    }
    ...
}
```

or:
```
jlink {
    jpackage {
        jvmArgs = ['-Duser.dir=my/user/dir']
        ...
    }
    ...
}
```

**Comment by nemphys** [comment]
I used the unix script template because I need to set the user.dir to a path detected at runtime (which is not possible to do in build.gradle).
It makes me wonder, though, since it works fine with the previous version of jpackage and breaks with the latest.

**Comment by DJViking** [comment]
The jpackage is still under development and might change. The latest build is almost a month old.
https://jdk.java.net/jpackage/

If you have problems with jpackage I suggest you subscribe to the core-libs-dev@openjdk.java.net mailinglist. The developers are taking in feedback from the community, so it is still possible to influence the development of jpackage (to a degree). It is not a support mailinglist, but you can report problems and bugs you experience with jpackage.

**Comment by nemphys** [comment]
Just checked with the latest version of jpackage and this still applies.
I am closing the issue, though, since the observed behaviour change not the plugin's fault.
