### ISSUE TITLE
Spaces in launcher name lead to invalid .pkg on Mac

### ISSUE THREAD

**Issue by jpd236** [beryx/badass-jlink-plugin#90]
Steps to reproduce on Mac OS X 10.14.6 and openjdk-14-jpackage+1-35_osx-x64_bin:

1. `git clone https://github.com/beryx/fxgl-sliding-puzzle.git`
2. Edit build.gradle to disable --mac-sign flag (since I don't have a cert)
2. Run `BADASS_JLINK_JPACKAGE_HOME={path/to/jdk14} ./gradlew jpackage`
3. Observe that build/jpackage/sliding-puzzle.pkg is valid:

```
$ du -sh build/jpackage/sliding-puzzle-1.0.pkg 
 50M	build/jpackage/sliding-puzzle-1.0.pkg
```

4. Edit `build.gradle` and change the launcher name from 'sliding-puzzle' to 'sliding puzzle'
5. Rerun `./gradlew jpackage`
6. Observe that the .pkg file is now seemingly invalid (way too small):

```
$ du -sh build/jpackage/sliding\ puzzle-1.0.pkg 
4.0K	build/jpackage/sliding puzzle-1.0.pkg
```

The .app and .dmg file seem to be fine, though.

**Comment by siordache** [comment]
I don't have access to a Mac, but I suspect it is a bug in the jpackage tool itself. There are several whitespace-related issues (resolved or still open) for jpackage in the JDK bug tracker, involving [java-options](https://bugs.openjdk.java.net/browse/JDK-8227641), [jvm-args](https://bugs.openjdk.java.net/browse/JDK-8207022), or [application name](https://bugs.openjdk.java.net/browse/JDK-8217331).

Maybe you can create a [SSCCE](http://sscce.org/) that reproduces the problem using only command-line tools (javac, jlink, and jpackage). If you succeed, please report this issue to the [core-libs-dev mailing list](https://mail.openjdk.java.net/mailman/listinfo/core-libs-dev).

**Comment by jpd236** [comment]
Reported upstream at https://mail.openjdk.java.net/pipermail/core-libs-dev/2019-September/062643.html
