### ISSUE TITLE
Add a version option for the merged module

### ISSUE THREAD

**Issue by nemphys** [beryx/badass-jlink-plugin#93]
It would be nice to be able to specify a version for the produced merged module (a parameter that would work like the built in gradle version parameter).
I can think of many reasons for this, but in my case it would help with dynamic updating frameworks (like update4j).

**Comment by siordache** [comment]
In 2.16.1 I added the `mergedModuleJarVersion` property.
default value: `project.version`

**Comment by nemphys** [comment]
Great, closed!
