### ISSUE TITLE
problem with unicode application parameters (Japanese) 

### ISSUE THREAD

**Issue by matintokyo** [beryx/badass-jlink-plugin#96]
Hi, thanks you for this excellent plugin.
I am not sure if this is caused by the plugin, but I have problem with unicode (Japanese) characters when used as application parameters.

This happens using file association in Windows: I double click a file in Windows Explorer, which opens the Java Application and passes the double-clicked file name as parameter.

This works without problems when using the myapp.bat generated by jlink, however, when I try to use myapp.exe generated by jpackage, the encoding is not recognized properly, and the parameter text is garbled.

Thank you for any insights on the matter!

**Comment by siordache** [comment]
This seems to be a [known issue](https://stackoverflow.com/questions/7660651/passing-command-line-unicode-argument-to-java-code) with Windows and Java.

Try to recover the parameter text with this code:

```
String filePath = new String(args.get(0).getBytes(
	java.nio.charset.Charset.defaultCharset()),
	java.nio.charset.StandardCharsets.UTF_8);
```

**Comment by matintokyo** [comment]
Thank you for your kind reply with insights and code!
Noted that this is an issue with Windows and Java.

Unfortunately, the workaround code you kindly provided does not fix the issue and the filepath is still garbled. 

Feel free to close this issue if not related to the plugin!
Thanks
