### ISSUE TITLE
splash and $APPDIR

### ISSUE THREAD

**Issue by batraz90** [beryx/badass-jlink-plugin#97]
I've been trying to make `-splash` work with jpackage but it doesn't seem to work. I've found https://bugs.openjdk.java.net/browse/JDK-8231910 and tried to use it way it was described in the link but it doesn't seem to work.

```
jlink {
    launcher {
        name = 'app'
    }
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    addExtraDependencies("javafx")

    jpackage {
        imageName = "app"
        imageOptions = ['--java-options', '-splash:$APPDIR/resources/splash.png']
        jpackageHome = "C:/Program Files/Java/jpackage"
    }
}
```
Is it even possible with this plugin or am I doing something wrong?

**Comment by alexeysemenyuk** [comment]
Hi, I'm jpackage developer. Hope I can help shed light on how it is working (and not working).

How would "splash.png" be deposited in "$APPDIR/resources" folder? I don't see how this would happen from this code snippet.

When you need to add custom resources to application image you should run jpackage in two phase mode. In the first phase you create application image. In the second phase you pack this application image in platform package specifying path to application image created in the the first phase with "--app-image" option. To add splash screen to your app this should look something like this:

Create application image:
`jpackage --package-type app-image --name MyApp --dest output`

Add splash screen source file to application image on Linux:
`cp my_splash.png output/MyApp/lib/app/resources/splash.png`

Add splash screen source file to application image on Linux:
`cp my_splash.png output/MyApp/app/resources/splash.png`

Create package from application image:
`jpackage --name MyApp --dest output --java-options '-splash:$APPDIR/resources/splash.png' --app-image output/MyApp`

In general, when app launchers created by jpackage don't work as expected I'd recommend running them with "_JAVA_LAUNCHER_DEBUG" environment variable set to 1 to debug JVM startup. Setting this environment variable would produce trace of arguments JVM was launched with.
Another option is to inspect contents of .cfg file in "app" subdirectory of application image created by jpackage.

I'm not sure two phase package building is supported in this plugin at the moment.

**Comment by siordache** [comment]
@alexeysemenyuk: Thanks for the explanations! The _JAVA_LAUNCHER_DEBUG environment variable is very useful. I didn't know about it.
The plugin runs jpackage in two phase mode to allow adding additional resources or adjusting the content of the .cfg file.

@batraz90: I updated the [badass-jlink-example-richtextfx](https://github.com/beryx-gist/badass-jlink-example-richtextfx) to display a splash screen.
As explained by @alexeysemenyuk, you need to copy you splash.png into the $APPDIR folder. You can do this [after the jpackageImage task](https://github.com/beryx-gist/badass-jlink-example-richtextfx/blob/4795ab713edd137aa65f50b8d6c7cc29f8c650f3/build.gradle#L44-L50):
```
tasks.jpackageImage.doLast {
    copy {
        from "src/main/resources"
        include "splash.png"
        into "build/jpackage/$project.name/app"
    }
}
```

Then you [configure the `-splash` option](https://github.com/beryx-gist/badass-jlink-example-richtextfx/blob/4795ab713edd137aa65f50b8d6c7cc29f8c650f3/build.gradle#L30) in the `jvmArgs` property (not in `imageOptions `):
```
jpackage {
    jvmArgs = ['-splash:$APPDIR/splash.png']
}
```

Also, make sure to use the latest [jpackage build](https://jdk.java.net/jpackage/) (14-jpackage+1-67, 2019/11/4).
