### ISSUE TITLE
Heads up for jpackage command line changes

### ISSUE THREAD

**Issue by alexeysemenyuk** [beryx/badass-jlink-plugin#98]
Hi, just want to give a heads up on the ongoing changes in jpackage CLI:
https://bugs.openjdk.java.net/browse/JDK-8233594
https://bugs.openjdk.java.net/browse/JDK-8233592

**Comment by siordache** [comment]
Thanks for the links, Alexey! It's good to know in advance about these changes.

**Comment by hohonuuli** [comment]
As a followup ... the latest release of jpackage has already made the breaking change from using `--package-type` to `--type`

**Comment by siordache** [comment]
Thanks for the update, @hohonuuli! I just released 2.16.4, which is compatible with the latesr jpackage build.

**Comment by hohonuuli** [comment]
@siordache Thank you for the update. You save me a lot of build grief! Also, since I have your attention ... I wanted to thank you for all your work on this plugin. It's been fantastically useful for me. Cheers!

**Comment by siordache** [comment]
Thanks @hohonuuli, you just made my day!
